/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.8 */
/* Thu Apr 24 21:00:40 2025 */

/* parameterized module instance */
iddrx2f __ (.alignwd( ), .clkin( ), .dcntl( ), .ready( ), .sclk( ), 
    .sync_clk( ), .sync_reset( ), .update( ), .datain( ), .q( ));
