/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.1 */
/* Mon Oct 21 19:26:02 2024 */

/* parameterized module instance */
synfifo_data_2048x8 __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .Q( ), .Empty( ), .Full( ));
