/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 4.9 */
/* Sat Aug 31 15:43:28 2024 */

/* parameterized module instance */
multiplier __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), .DataB( ), 
    .Result( ));
