/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 6.5 */
/* Mon Mar 20 10:59:18 2023 */

/* parameterized module instance */
opto_ram __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), .RdClock( ), 
    .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), .Q( ));
