/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.1 */
/* Thu Nov 21 11:06:10 2024 */

/* parameterized module instance */
sfifo_128x96 __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), 
    .Q( ), .Empty( ), .Full( ));
