/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 6.5 */
/* Sun Jun 06 19:09:19 2021 */

/* parameterized module instance */
distance_ram __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), 
    .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), 
    .Q( ));
