/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 4.9 */
/* Mon May 12 11:22:34 2025 */

/* parameterized module instance */
multiplier_16x8 __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), .DataB( ), 
    .Result( ));
