/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Tue Aug 09 09:27:45 2022 */

/* parameterized module instance */
C200_PLL __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ));
