/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.1 */
/* Thu Dec 19 10:54:08 2024 */

/* parameterized module instance */
sfifo128x88 __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), 
    .Q( ), .Empty( ), .Full( ));
