/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.1 */
/* Tue Oct 15 10:38:00 2024 */

/* parameterized module instance */
fifo_mac_frame_2048x10 __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .Q( ), .Empty( ), .Full( ));
