/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 4.9 */
/* E:\tools\Iscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n multiplier -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type dspmult -simple_portname -widtha 16 -widthb 16 -widthp 32 -PL_stages 3 -input_reg -output_reg -clk0 -ce0 -rst0 -fdc D:/programs/fpga/C200_FPGA_MS1004/C200_FPGA_MS1004_20210712/C200_FPGA/multiplier/multiplier.fdc  */
/* Mon Jul 12 10:54:19 2021 */


`timescale 1 ns / 1 ps
module multiplier (Clock, ClkEn, Aclr, DataA, DataB, Result)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Aclr;
    input wire [15:0] DataA;
    input wire [15:0] DataB;
    output wire [31:0] Result;

    wire multiplier_or2_0;
    wire multiplier_or1_0;
    wire multiplier_or2_1;
    wire multiplier_or1_1;
    wire multiplier_or2_2;
    wire multiplier_or1_2;
    wire multiplier_or2_3;
    wire multiplier_or1_3;
    wire multiplier_or2_4;
    wire multiplier_or1_4;
    wire multiplier_or2_5;
    wire multiplier_or1_5;
    wire multiplier_or2_6;
    wire multiplier_or1_6;
    wire multiplier_or2_7;
    wire multiplier_or1_7;
    wire multiplier_or2_8;
    wire multiplier_or1_8;
    wire multiplier_or2_9;
    wire multiplier_or1_9;
    wire multiplier_or2_10;
    wire multiplier_or1_10;
    wire multiplier_or2_11;
    wire multiplier_or1_11;
    wire multiplier_or2_12;
    wire multiplier_or1_12;
    wire multiplier_or2_13;
    wire multiplier_or1_13;
    wire multiplier_or2_14;
    wire multiplier_or1_14;
    wire multiplier_or2_15;
    wire multiplier_or1_15;
    wire multiplier_or2_16;
    wire multiplier_or1_16;
    wire multiplier_or2_17;
    wire multiplier_or1_17;
    wire multiplier_or2_18;
    wire multiplier_or1_18;
    wire multiplier_or2_19;
    wire multiplier_or1_19;
    wire multiplier_or2_20;
    wire multiplier_or1_20;
    wire multiplier_or2_21;
    wire multiplier_or1_21;
    wire multiplier_or2_22;
    wire multiplier_or1_22;
    wire multiplier_or2_23;
    wire multiplier_or1_23;
    wire multiplier_or2_24;
    wire multiplier_or1_24;
    wire multiplier_or2_25;
    wire multiplier_or1_25;
    wire multiplier_or2_26;
    wire multiplier_or1_26;
    wire multiplier_or2_27;
    wire multiplier_or1_27;
    wire multiplier_or2_28;
    wire multiplier_or1_28;
    wire multiplier_or2_29;
    wire multiplier_or1_29;
    wire multiplier_or2_30;
    wire multiplier_or1_30;
    wire multiplier_or2_31;
    wire multiplier_or1_31;
    wire multiplier_mult_direct_out_1_35;
    wire multiplier_mult_direct_out_1_34;
    wire multiplier_mult_direct_out_1_33;
    wire multiplier_mult_direct_out_1_32;
    wire multiplier_mult_direct_out_1_31;
    wire multiplier_mult_direct_out_1_30;
    wire multiplier_mult_direct_out_1_29;
    wire multiplier_mult_direct_out_1_28;
    wire multiplier_mult_direct_out_1_27;
    wire multiplier_mult_direct_out_1_26;
    wire multiplier_mult_direct_out_1_25;
    wire multiplier_mult_direct_out_1_24;
    wire multiplier_mult_direct_out_1_23;
    wire multiplier_mult_direct_out_1_22;
    wire multiplier_mult_direct_out_1_21;
    wire multiplier_mult_direct_out_1_20;
    wire multiplier_mult_direct_out_1_19;
    wire multiplier_mult_direct_out_1_18;
    wire multiplier_mult_direct_out_1_17;
    wire multiplier_mult_direct_out_1_16;
    wire multiplier_mult_direct_out_1_15;
    wire multiplier_mult_direct_out_1_14;
    wire multiplier_mult_direct_out_1_13;
    wire multiplier_mult_direct_out_1_12;
    wire multiplier_mult_direct_out_1_11;
    wire multiplier_mult_direct_out_1_10;
    wire multiplier_mult_direct_out_1_9;
    wire multiplier_mult_direct_out_1_8;
    wire multiplier_mult_direct_out_1_7;
    wire multiplier_mult_direct_out_1_6;
    wire multiplier_mult_direct_out_1_5;
    wire multiplier_mult_direct_out_1_4;
    wire multiplier_mult_direct_out_1_3;
    wire multiplier_mult_direct_out_1_2;
    wire multiplier_mult_direct_out_1_1;
    wire multiplier_mult_direct_out_1_0;
    wire scuba_vhi;
    wire scuba_vlo;

    FD1P3DX FF_63 (.D(multiplier_or2_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_62 (.D(multiplier_or2_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_61 (.D(multiplier_or2_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_60 (.D(multiplier_or2_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_59 (.D(multiplier_or2_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_58 (.D(multiplier_or2_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_57 (.D(multiplier_or2_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_56 (.D(multiplier_or2_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_55 (.D(multiplier_or2_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_54 (.D(multiplier_or2_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_53 (.D(multiplier_or2_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_52 (.D(multiplier_or2_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_51 (.D(multiplier_or2_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_50 (.D(multiplier_or2_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(multiplier_or2_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[14]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(multiplier_or2_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[15]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_47 (.D(multiplier_or2_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[16]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(multiplier_or2_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[17]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_45 (.D(multiplier_or2_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[18]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_44 (.D(multiplier_or2_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[19]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(multiplier_or2_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[20]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(multiplier_or2_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[21]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(multiplier_or2_22), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[22]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(multiplier_or2_23), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[23]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(multiplier_or2_24), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[24]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(multiplier_or2_25), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[25]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(multiplier_or2_26), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[26]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(multiplier_or2_27), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[27]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(multiplier_or2_28), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[28]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(multiplier_or2_29), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[29]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(multiplier_or2_30), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[30]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(multiplier_or2_31), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(Result[31]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(multiplier_or1_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(multiplier_or1_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(multiplier_or1_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(multiplier_or1_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(multiplier_or1_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(multiplier_or1_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(multiplier_or1_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(multiplier_or1_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(multiplier_or1_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(multiplier_or1_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(multiplier_or1_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(multiplier_or1_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(multiplier_or1_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(multiplier_or1_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(multiplier_or1_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(multiplier_or1_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(multiplier_or1_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(multiplier_or1_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(multiplier_or1_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_18))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(multiplier_or1_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_19))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(multiplier_or1_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_20))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(multiplier_or1_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_21))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(multiplier_or1_22), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_22))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(multiplier_or1_23), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_23))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(multiplier_or1_24), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_24))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(multiplier_or1_25), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_25))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(multiplier_or1_26), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_26))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(multiplier_or1_27), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_27))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(multiplier_or1_28), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_28))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(multiplier_or1_29), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_29))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(multiplier_or1_30), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_30))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(multiplier_or1_31), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(multiplier_or2_31))
             /* synthesis GSR="ENABLED" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam dsp_mult_0.CLK3_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK2_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK1_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK0_DIV = "ENABLED" ;
    defparam dsp_mult_0.HIGHSPEED_CLK = "NONE" ;
    defparam dsp_mult_0.REG_INPUTC_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTC_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTC_CLK = "NONE" ;
    defparam dsp_mult_0.SOURCEB_MODE = "B_SHIFT" ;
    defparam dsp_mult_0.MULT_BYPASS = "DISABLED" ;
    defparam dsp_mult_0.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_0.RESETMODE = "ASYNC" ;
    defparam dsp_mult_0.GSR = "ENABLED" ;
    defparam dsp_mult_0.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_mult_0.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_mult_0.REG_OUTPUT_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_0.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_mult_0.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTB_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTA_CLK = "CLK0" ;
    MULT18X18D dsp_mult_0 (.A17(DataA[15]), .A16(DataA[14]), .A15(DataA[13]), 
        .A14(DataA[12]), .A13(DataA[11]), .A12(DataA[10]), .A11(DataA[9]), 
        .A10(DataA[8]), .A9(DataA[7]), .A8(DataA[6]), .A7(DataA[5]), .A6(DataA[4]), 
        .A5(DataA[3]), .A4(DataA[2]), .A3(DataA[1]), .A2(DataA[0]), .A1(scuba_vlo), 
        .A0(scuba_vlo), .B17(DataB[15]), .B16(DataB[14]), .B15(DataB[13]), 
        .B14(DataB[12]), .B13(DataB[11]), .B12(DataB[10]), .B11(DataB[9]), 
        .B10(DataB[8]), .B9(DataB[7]), .B8(DataB[6]), .B7(DataB[5]), .B6(DataB[4]), 
        .B5(DataB[3]), .B4(DataB[2]), .B3(DataB[1]), .B2(DataB[0]), .B1(scuba_vlo), 
        .B0(scuba_vlo), .C17(scuba_vlo), .C16(scuba_vlo), .C15(scuba_vlo), 
        .C14(scuba_vlo), .C13(scuba_vlo), .C12(scuba_vlo), .C11(scuba_vlo), 
        .C10(scuba_vlo), .C9(scuba_vlo), .C8(scuba_vlo), .C7(scuba_vlo), 
        .C6(scuba_vlo), .C5(scuba_vlo), .C4(scuba_vlo), .C3(scuba_vlo), 
        .C2(scuba_vlo), .C1(scuba_vlo), .C0(scuba_vlo), .SIGNEDA(scuba_vlo), 
        .SIGNEDB(scuba_vlo), .SOURCEA(scuba_vlo), .SOURCEB(scuba_vlo), .CE0(ClkEn), 
        .CE1(scuba_vhi), .CE2(scuba_vhi), .CE3(scuba_vhi), .CLK0(Clock), 
        .CLK1(scuba_vlo), .CLK2(scuba_vlo), .CLK3(scuba_vlo), .RST0(Aclr), 
        .RST1(scuba_vlo), .RST2(scuba_vlo), .RST3(scuba_vlo), .SRIA17(scuba_vlo), 
        .SRIA16(scuba_vlo), .SRIA15(scuba_vlo), .SRIA14(scuba_vlo), .SRIA13(scuba_vlo), 
        .SRIA12(scuba_vlo), .SRIA11(scuba_vlo), .SRIA10(scuba_vlo), .SRIA9(scuba_vlo), 
        .SRIA8(scuba_vlo), .SRIA7(scuba_vlo), .SRIA6(scuba_vlo), .SRIA5(scuba_vlo), 
        .SRIA4(scuba_vlo), .SRIA3(scuba_vlo), .SRIA2(scuba_vlo), .SRIA1(scuba_vlo), 
        .SRIA0(scuba_vlo), .SRIB17(scuba_vlo), .SRIB16(scuba_vlo), .SRIB15(scuba_vlo), 
        .SRIB14(scuba_vlo), .SRIB13(scuba_vlo), .SRIB12(scuba_vlo), .SRIB11(scuba_vlo), 
        .SRIB10(scuba_vlo), .SRIB9(scuba_vlo), .SRIB8(scuba_vlo), .SRIB7(scuba_vlo), 
        .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), .SRIB4(scuba_vlo), .SRIB3(scuba_vlo), 
        .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), .SRIB0(scuba_vlo), .SROA17(), 
        .SROA16(), .SROA15(), .SROA14(), .SROA13(), .SROA12(), .SROA11(), 
        .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), .SROA5(), .SROA4(), 
        .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), .SROB16(), .SROB15(), 
        .SROB14(), .SROB13(), .SROB12(), .SROB11(), .SROB10(), .SROB9(), 
        .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), .SROB3(), .SROB2(), 
        .SROB1(), .SROB0(), .ROA17(), .ROA16(), .ROA15(), .ROA14(), .ROA13(), 
        .ROA12(), .ROA11(), .ROA10(), .ROA9(), .ROA8(), .ROA7(), .ROA6(), 
        .ROA5(), .ROA4(), .ROA3(), .ROA2(), .ROA1(), .ROA0(), .ROB17(), 
        .ROB16(), .ROB15(), .ROB14(), .ROB13(), .ROB12(), .ROB11(), .ROB10(), 
        .ROB9(), .ROB8(), .ROB7(), .ROB6(), .ROB5(), .ROB4(), .ROB3(), .ROB2(), 
        .ROB1(), .ROB0(), .ROC17(), .ROC16(), .ROC15(), .ROC14(), .ROC13(), 
        .ROC12(), .ROC11(), .ROC10(), .ROC9(), .ROC8(), .ROC7(), .ROC6(), 
        .ROC5(), .ROC4(), .ROC3(), .ROC2(), .ROC1(), .ROC0(), .P35(multiplier_mult_direct_out_1_35), 
        .P34(multiplier_mult_direct_out_1_34), .P33(multiplier_mult_direct_out_1_33), 
        .P32(multiplier_mult_direct_out_1_32), .P31(multiplier_mult_direct_out_1_31), 
        .P30(multiplier_mult_direct_out_1_30), .P29(multiplier_mult_direct_out_1_29), 
        .P28(multiplier_mult_direct_out_1_28), .P27(multiplier_mult_direct_out_1_27), 
        .P26(multiplier_mult_direct_out_1_26), .P25(multiplier_mult_direct_out_1_25), 
        .P24(multiplier_mult_direct_out_1_24), .P23(multiplier_mult_direct_out_1_23), 
        .P22(multiplier_mult_direct_out_1_22), .P21(multiplier_mult_direct_out_1_21), 
        .P20(multiplier_mult_direct_out_1_20), .P19(multiplier_mult_direct_out_1_19), 
        .P18(multiplier_mult_direct_out_1_18), .P17(multiplier_mult_direct_out_1_17), 
        .P16(multiplier_mult_direct_out_1_16), .P15(multiplier_mult_direct_out_1_15), 
        .P14(multiplier_mult_direct_out_1_14), .P13(multiplier_mult_direct_out_1_13), 
        .P12(multiplier_mult_direct_out_1_12), .P11(multiplier_mult_direct_out_1_11), 
        .P10(multiplier_mult_direct_out_1_10), .P9(multiplier_mult_direct_out_1_9), 
        .P8(multiplier_mult_direct_out_1_8), .P7(multiplier_mult_direct_out_1_7), 
        .P6(multiplier_mult_direct_out_1_6), .P5(multiplier_mult_direct_out_1_5), 
        .P4(multiplier_mult_direct_out_1_4), .P3(multiplier_mult_direct_out_1_3), 
        .P2(multiplier_mult_direct_out_1_2), .P1(multiplier_mult_direct_out_1_1), 
        .P0(multiplier_mult_direct_out_1_0), .SIGNEDP());

    assign multiplier_or1_31 = multiplier_mult_direct_out_1_35;
    assign multiplier_or1_30 = multiplier_mult_direct_out_1_34;
    assign multiplier_or1_29 = multiplier_mult_direct_out_1_33;
    assign multiplier_or1_28 = multiplier_mult_direct_out_1_32;
    assign multiplier_or1_27 = multiplier_mult_direct_out_1_31;
    assign multiplier_or1_26 = multiplier_mult_direct_out_1_30;
    assign multiplier_or1_25 = multiplier_mult_direct_out_1_29;
    assign multiplier_or1_24 = multiplier_mult_direct_out_1_28;
    assign multiplier_or1_23 = multiplier_mult_direct_out_1_27;
    assign multiplier_or1_22 = multiplier_mult_direct_out_1_26;
    assign multiplier_or1_21 = multiplier_mult_direct_out_1_25;
    assign multiplier_or1_20 = multiplier_mult_direct_out_1_24;
    assign multiplier_or1_19 = multiplier_mult_direct_out_1_23;
    assign multiplier_or1_18 = multiplier_mult_direct_out_1_22;
    assign multiplier_or1_17 = multiplier_mult_direct_out_1_21;
    assign multiplier_or1_16 = multiplier_mult_direct_out_1_20;
    assign multiplier_or1_15 = multiplier_mult_direct_out_1_19;
    assign multiplier_or1_14 = multiplier_mult_direct_out_1_18;
    assign multiplier_or1_13 = multiplier_mult_direct_out_1_17;
    assign multiplier_or1_12 = multiplier_mult_direct_out_1_16;
    assign multiplier_or1_11 = multiplier_mult_direct_out_1_15;
    assign multiplier_or1_10 = multiplier_mult_direct_out_1_14;
    assign multiplier_or1_9 = multiplier_mult_direct_out_1_13;
    assign multiplier_or1_8 = multiplier_mult_direct_out_1_12;
    assign multiplier_or1_7 = multiplier_mult_direct_out_1_11;
    assign multiplier_or1_6 = multiplier_mult_direct_out_1_10;
    assign multiplier_or1_5 = multiplier_mult_direct_out_1_9;
    assign multiplier_or1_4 = multiplier_mult_direct_out_1_8;
    assign multiplier_or1_3 = multiplier_mult_direct_out_1_7;
    assign multiplier_or1_2 = multiplier_mult_direct_out_1_6;
    assign multiplier_or1_1 = multiplier_mult_direct_out_1_5;
    assign multiplier_or1_0 = multiplier_mult_direct_out_1_4;


    // exemplar begin
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
