/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.8 */
/* D:\TOOL\LatticeDiamond\diamond\3.13\ispfpga\bin\nt64\scuba.exe -w -n asfifo_decode -lang verilog -synth synplify -bus_exp 7 -bb -arch sa5p00 -type ebfifo -depth 128 -width 10 -pfu_fifo -regout -no_enable -sync_reset -pe -1 -pf -1 -fdc D:/FreeWork/df1_second_round/df1_3dprj_dev/src/ip/df1_lidar_ip/asfifo_decode/asfifo_decode.fdc  */
/* Tue Apr 29 11:14:36 2025 */


`timescale 1 ns / 1 ps
module asfifo_decode (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, 
    Q, Empty, Full)/* synthesis NGD_DRC_MASK=1 */;
    input wire [9:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [9:0] Q;
    output wire Empty;
    output wire Full;

    wire invout_1;
    wire invout_0;
    wire func_and_inet;
    wire func_and_inet_1;
    wire func_and_inet_2;
    wire wptr_6_inv;
    wire func_and_inet_3;
    wire func_and_inet_4;
    wire wptr_5_inv;
    wire func_and_inet_5;
    wire wptr_4_inv;
    wire func_and_inet_6;
    wire func_and_inet_7;
    wire w_g2b_xor_cluster_1;
    wire r_g2b_xor_cluster_1;
    wire w_gdata_0;
    wire w_gdata_1;
    wire w_gdata_2;
    wire w_gdata_3;
    wire w_gdata_4;
    wire w_gdata_5;
    wire w_gdata_6;
    wire wptr_4;
    wire wptr_5;
    wire wptr_6;
    wire wptr_7;
    wire r_gdata_0;
    wire r_gdata_1;
    wire r_gdata_2;
    wire r_gdata_3;
    wire r_gdata_4;
    wire r_gdata_5;
    wire r_gdata_6;
    wire rptr_7;
    wire edataout0;
    wire edataout1;
    wire edataout2;
    wire edataout3;
    wire edataout4;
    wire edataout5;
    wire edataout6;
    wire edataout7;
    wire edataout8;
    wire edataout9;
    wire w_gcount_0;
    wire w_gcount_1;
    wire w_gcount_2;
    wire w_gcount_3;
    wire w_gcount_4;
    wire w_gcount_5;
    wire w_gcount_6;
    wire w_gcount_7;
    wire r_gcount_0;
    wire r_gcount_1;
    wire r_gcount_2;
    wire r_gcount_3;
    wire r_gcount_4;
    wire r_gcount_5;
    wire r_gcount_6;
    wire r_gcount_7;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire w_gcount_r22;
    wire w_gcount_r2;
    wire w_gcount_r23;
    wire w_gcount_r3;
    wire w_gcount_r24;
    wire w_gcount_r4;
    wire w_gcount_r25;
    wire w_gcount_r5;
    wire w_gcount_r26;
    wire w_gcount_r6;
    wire w_gcount_r27;
    wire w_gcount_r7;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire r_gcount_w22;
    wire r_gcount_w2;
    wire r_gcount_w23;
    wire r_gcount_w3;
    wire r_gcount_w24;
    wire r_gcount_w4;
    wire r_gcount_w25;
    wire r_gcount_w5;
    wire r_gcount_w26;
    wire r_gcount_w6;
    wire r_gcount_w27;
    wire r_gcount_w7;
    wire empty_i;
    wire rRst;
    wire full_i;
    wire iwcount_0;
    wire iwcount_1;
    wire w_gctr_ci;
    wire iwcount_2;
    wire iwcount_3;
    wire co0;
    wire iwcount_4;
    wire iwcount_5;
    wire co1;
    wire iwcount_6;
    wire iwcount_7;
    wire co3;
    wire co2;
    wire wcount_7;
    wire ircount_0;
    wire ircount_1;
    wire r_gctr_ci;
    wire ircount_2;
    wire ircount_3;
    wire co0_1;
    wire ircount_4;
    wire ircount_5;
    wire co1_1;
    wire ircount_6;
    wire ircount_7;
    wire co3_1;
    wire co2_1;
    wire rcount_7;
    wire rdataout9;
    wire rdataout8;
    wire rdataout7;
    wire rdataout6;
    wire rdataout5;
    wire rdataout4;
    wire rdataout3;
    wire rdataout2;
    wire rdataout1;
    wire rdataout0;
    wire rptr_6;
    wire rptr_5;
    wire rptr_4;
    wire rden_i;
    wire cmp_ci;
    wire wcount_r0;
    wire wcount_r1;
    wire rcount_0;
    wire rcount_1;
    wire co0_2;
    wire wcount_r2;
    wire wcount_r3;
    wire rcount_2;
    wire rcount_3;
    wire co1_2;
    wire w_g2b_xor_cluster_0;
    wire wcount_r5;
    wire rcount_4;
    wire rcount_5;
    wire co2_2;
    wire wcount_r6;
    wire empty_cmp_clr;
    wire rcount_6;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire wren_i;
    wire cmp_ci_1;
    wire rcount_w0;
    wire rcount_w1;
    wire wcount_0;
    wire wcount_1;
    wire co0_3;
    wire rcount_w2;
    wire rcount_w3;
    wire wcount_2;
    wire wcount_3;
    wire co1_3;
    wire r_g2b_xor_cluster_0;
    wire rcount_w5;
    wire wcount_4;
    wire wcount_5;
    wire co2_3;
    wire rcount_w6;
    wire full_cmp_clr;
    wire wcount_6;
    wire full_cmp_set;
    wire full_d;
    wire scuba_vlo;
    wire full_d_c;
    wire mdL0_0_9;
    wire mdL0_0_8;
    wire mdL0_0_7;
    wire mdL0_0_6;
    wire mdL0_0_5;
    wire mdL0_0_4;
    wire mdL0_0_3;
    wire mdL0_0_2;
    wire mdL0_0_1;
    wire mdL0_0_0;
    wire dec0_wre3;
    wire mdL0_1_9;
    wire mdL0_1_8;
    wire mdL0_1_7;
    wire mdL0_1_6;
    wire mdL0_1_5;
    wire mdL0_1_4;
    wire mdL0_1_3;
    wire mdL0_1_2;
    wire mdL0_1_1;
    wire mdL0_1_0;
    wire dec1_wre7;
    wire mdL0_2_9;
    wire mdL0_2_8;
    wire mdL0_2_7;
    wire mdL0_2_6;
    wire mdL0_2_5;
    wire mdL0_2_4;
    wire mdL0_2_3;
    wire mdL0_2_2;
    wire mdL0_2_1;
    wire mdL0_2_0;
    wire dec2_wre11;
    wire mdL0_3_9;
    wire mdL0_3_8;
    wire mdL0_3_7;
    wire mdL0_3_6;
    wire mdL0_3_5;
    wire mdL0_3_4;
    wire mdL0_3_3;
    wire mdL0_3_2;
    wire mdL0_3_1;
    wire mdL0_3_0;
    wire dec3_wre15;
    wire mdL0_4_9;
    wire mdL0_4_8;
    wire mdL0_4_7;
    wire mdL0_4_6;
    wire mdL0_4_5;
    wire mdL0_4_4;
    wire mdL0_4_3;
    wire mdL0_4_2;
    wire mdL0_4_1;
    wire mdL0_4_0;
    wire dec4_wre19;
    wire mdL0_5_9;
    wire mdL0_5_8;
    wire mdL0_5_7;
    wire mdL0_5_6;
    wire mdL0_5_5;
    wire mdL0_5_4;
    wire mdL0_5_3;
    wire mdL0_5_2;
    wire mdL0_5_1;
    wire mdL0_5_0;
    wire dec5_wre23;
    wire mdL0_6_9;
    wire mdL0_6_8;
    wire mdL0_6_7;
    wire mdL0_6_6;
    wire mdL0_6_5;
    wire mdL0_6_4;
    wire mdL0_6_3;
    wire mdL0_6_2;
    wire mdL0_6_1;
    wire mdL0_6_0;
    wire dec6_wre27;
    wire mdL0_7_9;
    wire mdL0_7_8;
    wire scuba_vhi;
    wire mdL0_7_7;
    wire mdL0_7_6;
    wire mdL0_7_5;
    wire mdL0_7_4;
    wire mdL0_7_3;
    wire mdL0_7_2;
    wire mdL0_7_1;
    wire mdL0_7_0;
    wire rptr_3;
    wire rptr_2;
    wire rptr_1;
    wire rptr_0;
    wire dec7_wre31;
    wire wptr_3;
    wire wptr_2;
    wire wptr_1;
    wire wptr_0;

    AND2 AND2_t16 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_4 (.A(full_i), .Z(invout_1));

    AND2 AND2_t15 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_3 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t14 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t13 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t12 (.A(wcount_1), .B(wcount_2), .Z(w_gdata_1));

    XOR2 XOR2_t11 (.A(wcount_2), .B(wcount_3), .Z(w_gdata_2));

    XOR2 XOR2_t10 (.A(wcount_3), .B(wcount_4), .Z(w_gdata_3));

    XOR2 XOR2_t9 (.A(wcount_4), .B(wcount_5), .Z(w_gdata_4));

    XOR2 XOR2_t8 (.A(wcount_5), .B(wcount_6), .Z(w_gdata_5));

    XOR2 XOR2_t7 (.A(wcount_6), .B(wcount_7), .Z(w_gdata_6));

    XOR2 XOR2_t6 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    XOR2 XOR2_t5 (.A(rcount_1), .B(rcount_2), .Z(r_gdata_1));

    XOR2 XOR2_t4 (.A(rcount_2), .B(rcount_3), .Z(r_gdata_2));

    XOR2 XOR2_t3 (.A(rcount_3), .B(rcount_4), .Z(r_gdata_3));

    XOR2 XOR2_t2 (.A(rcount_4), .B(rcount_5), .Z(r_gdata_4));

    XOR2 XOR2_t1 (.A(rcount_5), .B(rcount_6), .Z(r_gdata_5));

    XOR2 XOR2_t0 (.A(rcount_6), .B(rcount_7), .Z(r_gdata_6));

    INV INV_2 (.A(wptr_4), .Z(wptr_4_inv));

    INV INV_1 (.A(wptr_5), .Z(wptr_5_inv));

    INV INV_0 (.A(wptr_6), .Z(wptr_6_inv));

    defparam LUT4_35.initval =  16'h8000 ;
    ROM16X1A LUT4_35 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4_inv), .AD0(wptr_5_inv), 
        .DO0(func_and_inet));

    defparam LUT4_34.initval =  16'h8000 ;
    ROM16X1A LUT4_34 (.AD3(func_and_inet), .AD2(wptr_6_inv), .AD1(scuba_vhi), 
        .AD0(scuba_vhi), .DO0(dec0_wre3));

    defparam LUT4_33.initval =  16'h8000 ;
    ROM16X1A LUT4_33 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4), .AD0(wptr_5_inv), 
        .DO0(func_and_inet_1));

    defparam LUT4_32.initval =  16'h8000 ;
    ROM16X1A LUT4_32 (.AD3(func_and_inet_1), .AD2(wptr_6_inv), .AD1(scuba_vhi), 
        .AD0(scuba_vhi), .DO0(dec1_wre7));

    defparam LUT4_31.initval =  16'h8000 ;
    ROM16X1A LUT4_31 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4_inv), .AD0(wptr_5), 
        .DO0(func_and_inet_2));

    defparam LUT4_30.initval =  16'h8000 ;
    ROM16X1A LUT4_30 (.AD3(func_and_inet_2), .AD2(wptr_6_inv), .AD1(scuba_vhi), 
        .AD0(scuba_vhi), .DO0(dec2_wre11));

    defparam LUT4_29.initval =  16'h8000 ;
    ROM16X1A LUT4_29 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4), .AD0(wptr_5), 
        .DO0(func_and_inet_3));

    defparam LUT4_28.initval =  16'h8000 ;
    ROM16X1A LUT4_28 (.AD3(func_and_inet_3), .AD2(wptr_6_inv), .AD1(scuba_vhi), 
        .AD0(scuba_vhi), .DO0(dec3_wre15));

    defparam LUT4_27.initval =  16'h8000 ;
    ROM16X1A LUT4_27 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4_inv), .AD0(wptr_5_inv), 
        .DO0(func_and_inet_4));

    defparam LUT4_26.initval =  16'h8000 ;
    ROM16X1A LUT4_26 (.AD3(func_and_inet_4), .AD2(wptr_6), .AD1(scuba_vhi), 
        .AD0(scuba_vhi), .DO0(dec4_wre19));

    defparam LUT4_25.initval =  16'h8000 ;
    ROM16X1A LUT4_25 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4), .AD0(wptr_5_inv), 
        .DO0(func_and_inet_5));

    defparam LUT4_24.initval =  16'h8000 ;
    ROM16X1A LUT4_24 (.AD3(func_and_inet_5), .AD2(wptr_6), .AD1(scuba_vhi), 
        .AD0(scuba_vhi), .DO0(dec5_wre23));

    defparam LUT4_23.initval =  16'h8000 ;
    ROM16X1A LUT4_23 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4_inv), .AD0(wptr_5), 
        .DO0(func_and_inet_6));

    defparam LUT4_22.initval =  16'h8000 ;
    ROM16X1A LUT4_22 (.AD3(func_and_inet_6), .AD2(wptr_6), .AD1(scuba_vhi), 
        .AD0(scuba_vhi), .DO0(dec6_wre27));

    defparam LUT4_21.initval =  16'h8000 ;
    ROM16X1A LUT4_21 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4), .AD0(wptr_5), 
        .DO0(func_and_inet_7));

    defparam LUT4_20.initval =  16'h8000 ;
    ROM16X1A LUT4_20 (.AD3(func_and_inet_7), .AD2(wptr_6), .AD1(scuba_vhi), 
        .AD0(scuba_vhi), .DO0(dec7_wre31));

    defparam LUT4_19.initval =  16'h6996 ;
    ROM16X1A LUT4_19 (.AD3(w_gcount_r24), .AD2(w_gcount_r25), .AD1(w_gcount_r26), 
        .AD0(w_gcount_r27), .DO0(w_g2b_xor_cluster_0));

    defparam LUT4_18.initval =  16'h6996 ;
    ROM16X1A LUT4_18 (.AD3(w_gcount_r20), .AD2(w_gcount_r21), .AD1(w_gcount_r22), 
        .AD0(w_gcount_r23), .DO0(w_g2b_xor_cluster_1));

    defparam LUT4_17.initval =  16'h6996 ;
    ROM16X1A LUT4_17 (.AD3(w_gcount_r26), .AD2(w_gcount_r27), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r6));

    defparam LUT4_16.initval =  16'h6996 ;
    ROM16X1A LUT4_16 (.AD3(w_gcount_r25), .AD2(w_gcount_r26), .AD1(w_gcount_r27), 
        .AD0(scuba_vlo), .DO0(wcount_r5));

    defparam LUT4_15.initval =  16'h6996 ;
    ROM16X1A LUT4_15 (.AD3(w_gcount_r23), .AD2(w_gcount_r24), .AD1(w_gcount_r25), 
        .AD0(wcount_r6), .DO0(wcount_r3));

    defparam LUT4_14.initval =  16'h6996 ;
    ROM16X1A LUT4_14 (.AD3(w_gcount_r22), .AD2(w_gcount_r23), .AD1(w_gcount_r24), 
        .AD0(wcount_r5), .DO0(wcount_r2));

    defparam LUT4_13.initval =  16'h6996 ;
    ROM16X1A LUT4_13 (.AD3(w_gcount_r21), .AD2(w_gcount_r22), .AD1(w_gcount_r23), 
        .AD0(w_g2b_xor_cluster_0), .DO0(wcount_r1));

    defparam LUT4_12.initval =  16'h6996 ;
    ROM16X1A LUT4_12 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(wcount_r0));

    defparam LUT4_11.initval =  16'h6996 ;
    ROM16X1A LUT4_11 (.AD3(r_gcount_w24), .AD2(r_gcount_w25), .AD1(r_gcount_w26), 
        .AD0(r_gcount_w27), .DO0(r_g2b_xor_cluster_0));

    defparam LUT4_10.initval =  16'h6996 ;
    ROM16X1A LUT4_10 (.AD3(r_gcount_w20), .AD2(r_gcount_w21), .AD1(r_gcount_w22), 
        .AD0(r_gcount_w23), .DO0(r_g2b_xor_cluster_1));

    defparam LUT4_9.initval =  16'h6996 ;
    ROM16X1A LUT4_9 (.AD3(r_gcount_w26), .AD2(r_gcount_w27), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w6));

    defparam LUT4_8.initval =  16'h6996 ;
    ROM16X1A LUT4_8 (.AD3(r_gcount_w25), .AD2(r_gcount_w26), .AD1(r_gcount_w27), 
        .AD0(scuba_vlo), .DO0(rcount_w5));

    defparam LUT4_7.initval =  16'h6996 ;
    ROM16X1A LUT4_7 (.AD3(r_gcount_w23), .AD2(r_gcount_w24), .AD1(r_gcount_w25), 
        .AD0(rcount_w6), .DO0(rcount_w3));

    defparam LUT4_6.initval =  16'h6996 ;
    ROM16X1A LUT4_6 (.AD3(r_gcount_w22), .AD2(r_gcount_w23), .AD1(r_gcount_w24), 
        .AD0(rcount_w5), .DO0(rcount_w2));

    defparam LUT4_5.initval =  16'h6996 ;
    ROM16X1A LUT4_5 (.AD3(r_gcount_w21), .AD2(r_gcount_w22), .AD1(r_gcount_w23), 
        .AD0(r_g2b_xor_cluster_0), .DO0(rcount_w1));

    defparam LUT4_4.initval =  16'h6996 ;
    ROM16X1A LUT4_4 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1), 
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(rcount_w0));

    defparam LUT4_3.initval =  16'h0410 ;
    ROM16X1A LUT4_3 (.AD3(rptr_7), .AD2(rcount_7), .AD1(w_gcount_r27), .AD0(scuba_vlo), 
        .DO0(empty_cmp_set));

    defparam LUT4_2.initval =  16'h1004 ;
    ROM16X1A LUT4_2 (.AD3(rptr_7), .AD2(rcount_7), .AD1(w_gcount_r27), .AD0(scuba_vlo), 
        .DO0(empty_cmp_clr));

    defparam LUT4_1.initval =  16'h0140 ;
    ROM16X1A LUT4_1 (.AD3(wptr_7), .AD2(wcount_7), .AD1(r_gcount_w27), .AD0(scuba_vlo), 
        .DO0(full_cmp_set));

    defparam LUT4_0.initval =  16'h4001 ;
    ROM16X1A LUT4_0 (.AD3(wptr_7), .AD2(wcount_7), .AD1(r_gcount_w27), .AD0(scuba_vlo), 
        .DO0(full_cmp_clr));

    FD1P3BX FF_101 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_100 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_99 (.D(iwcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_98 (.D(iwcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_97 (.D(iwcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_96 (.D(iwcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_95 (.D(iwcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_94 (.D(iwcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_93 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_92 (.D(w_gdata_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_91 (.D(w_gdata_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_90 (.D(w_gdata_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_89 (.D(w_gdata_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_88 (.D(w_gdata_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_87 (.D(w_gdata_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_86 (.D(wcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_85 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_84 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_83 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_82 (.D(wcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_81 (.D(wcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_80 (.D(wcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_79 (.D(wcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_78 (.D(wcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_77 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_76 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_75 (.D(ircount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_74 (.D(ircount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_73 (.D(ircount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_72 (.D(ircount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_71 (.D(ircount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_70 (.D(ircount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_69 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_68 (.D(r_gdata_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_67 (.D(r_gdata_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_66 (.D(r_gdata_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_65 (.D(r_gdata_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_64 (.D(r_gdata_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_63 (.D(r_gdata_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_62 (.D(rcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(r_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_61 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_60 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_59 (.D(rcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_58 (.D(rcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_57 (.D(rcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_56 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_55 (.D(rcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_54 (.D(rcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_53 (.D(edataout0), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_52 (.D(rdataout0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_51 (.D(edataout1), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_50 (.D(rdataout1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(edataout2), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(rdataout2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_47 (.D(edataout3), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(rdataout3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_45 (.D(edataout4), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_44 (.D(rdataout4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(edataout5), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(rdataout5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(edataout6), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(rdataout6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(edataout7), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(rdataout7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(edataout8), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(rdataout8), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(edataout9), .SP(scuba_vhi), .CK(RdClock), .CD(rRst), 
        .Q(Q[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(rdataout9), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(edataout9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_33 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_32 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_31 (.D(w_gcount_2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_30 (.D(w_gcount_3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_29 (.D(w_gcount_4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_28 (.D(w_gcount_5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_27 (.D(w_gcount_6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_26 (.D(w_gcount_7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_25 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_24 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_23 (.D(r_gcount_2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_22 (.D(r_gcount_3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_21 (.D(r_gcount_4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_20 (.D(r_gcount_5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_19 (.D(r_gcount_6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_18 (.D(r_gcount_7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_17 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_16 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_15 (.D(w_gcount_r2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_14 (.D(w_gcount_r3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_13 (.D(w_gcount_r4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_12 (.D(w_gcount_r5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_11 (.D(w_gcount_r6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_10 (.D(w_gcount_r7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_9 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_8 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_7 (.D(r_gcount_w2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_6 (.D(r_gcount_w3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_5 (.D(r_gcount_w4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_4 (.D(r_gcount_w5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_3 (.D(r_gcount_w6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_2 (.D(r_gcount_w7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w27))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_1 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    defparam w_gctr_cia.INJECT1_1 = "NO" ;
    defparam w_gctr_cia.INJECT1_0 = "NO" ;
    defparam w_gctr_cia.INIT1 =  16'h66AA ;
    defparam w_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(w_gctr_ci));

    defparam w_gctr_0.INJECT1_1 = "NO" ;
    defparam w_gctr_0.INJECT1_0 = "NO" ;
    defparam w_gctr_0.INIT1 =  16'h66AA ;
    defparam w_gctr_0.INIT0 =  16'h66AA ;
    CCU2C w_gctr_0 (.A0(wcount_0), .A1(wcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(w_gctr_ci), .S0(iwcount_0), .S1(iwcount_1), .COUT(co0));

    defparam w_gctr_1.INJECT1_1 = "NO" ;
    defparam w_gctr_1.INJECT1_0 = "NO" ;
    defparam w_gctr_1.INIT1 =  16'h66AA ;
    defparam w_gctr_1.INIT0 =  16'h66AA ;
    CCU2C w_gctr_1 (.A0(wcount_2), .A1(wcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(iwcount_2), .S1(iwcount_3), .COUT(co1));

    defparam w_gctr_2.INJECT1_1 = "NO" ;
    defparam w_gctr_2.INJECT1_0 = "NO" ;
    defparam w_gctr_2.INIT1 =  16'h66AA ;
    defparam w_gctr_2.INIT0 =  16'h66AA ;
    CCU2C w_gctr_2 (.A0(wcount_4), .A1(wcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1), .S0(iwcount_4), .S1(iwcount_5), .COUT(co2));

    defparam w_gctr_3.INJECT1_1 = "NO" ;
    defparam w_gctr_3.INJECT1_0 = "NO" ;
    defparam w_gctr_3.INIT1 =  16'h66AA ;
    defparam w_gctr_3.INIT0 =  16'h66AA ;
    CCU2C w_gctr_3 (.A0(wcount_6), .A1(wcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2), .S0(iwcount_6), .S1(iwcount_7), .COUT(co3));

    defparam r_gctr_cia.INJECT1_1 = "NO" ;
    defparam r_gctr_cia.INJECT1_0 = "NO" ;
    defparam r_gctr_cia.INIT1 =  16'h66AA ;
    defparam r_gctr_cia.INIT0 =  16'h66AA ;
    CCU2C r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(r_gctr_ci));

    defparam r_gctr_0.INJECT1_1 = "NO" ;
    defparam r_gctr_0.INJECT1_0 = "NO" ;
    defparam r_gctr_0.INIT1 =  16'h66AA ;
    defparam r_gctr_0.INIT0 =  16'h66AA ;
    CCU2C r_gctr_0 (.A0(rcount_0), .A1(rcount_1), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(r_gctr_ci), .S0(ircount_0), .S1(ircount_1), .COUT(co0_1));

    defparam r_gctr_1.INJECT1_1 = "NO" ;
    defparam r_gctr_1.INJECT1_0 = "NO" ;
    defparam r_gctr_1.INIT1 =  16'h66AA ;
    defparam r_gctr_1.INIT0 =  16'h66AA ;
    CCU2C r_gctr_1 (.A0(rcount_2), .A1(rcount_3), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_1), .S0(ircount_2), .S1(ircount_3), .COUT(co1_1));

    defparam r_gctr_2.INJECT1_1 = "NO" ;
    defparam r_gctr_2.INJECT1_0 = "NO" ;
    defparam r_gctr_2.INIT1 =  16'h66AA ;
    defparam r_gctr_2.INIT0 =  16'h66AA ;
    CCU2C r_gctr_2 (.A0(rcount_4), .A1(rcount_5), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1_1), .S0(ircount_4), .S1(ircount_5), .COUT(co2_1));

    defparam r_gctr_3.INJECT1_1 = "NO" ;
    defparam r_gctr_3.INJECT1_0 = "NO" ;
    defparam r_gctr_3.INIT1 =  16'h66AA ;
    defparam r_gctr_3.INIT0 =  16'h66AA ;
    CCU2C r_gctr_3 (.A0(rcount_6), .A1(rcount_7), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2_1), .S0(ircount_6), .S1(ircount_7), .COUT(co3_1));

    MUX81 mux_9 (.D0(mdL0_0_9), .D1(mdL0_1_9), .D2(mdL0_2_9), .D3(mdL0_3_9), 
        .D4(mdL0_4_9), .D5(mdL0_5_9), .D6(mdL0_6_9), .D7(mdL0_7_9), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout9));

    MUX81 mux_8 (.D0(mdL0_0_8), .D1(mdL0_1_8), .D2(mdL0_2_8), .D3(mdL0_3_8), 
        .D4(mdL0_4_8), .D5(mdL0_5_8), .D6(mdL0_6_8), .D7(mdL0_7_8), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout8));

    MUX81 mux_7 (.D0(mdL0_0_7), .D1(mdL0_1_7), .D2(mdL0_2_7), .D3(mdL0_3_7), 
        .D4(mdL0_4_7), .D5(mdL0_5_7), .D6(mdL0_6_7), .D7(mdL0_7_7), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout7));

    MUX81 mux_6 (.D0(mdL0_0_6), .D1(mdL0_1_6), .D2(mdL0_2_6), .D3(mdL0_3_6), 
        .D4(mdL0_4_6), .D5(mdL0_5_6), .D6(mdL0_6_6), .D7(mdL0_7_6), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout6));

    MUX81 mux_5 (.D0(mdL0_0_5), .D1(mdL0_1_5), .D2(mdL0_2_5), .D3(mdL0_3_5), 
        .D4(mdL0_4_5), .D5(mdL0_5_5), .D6(mdL0_6_5), .D7(mdL0_7_5), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout5));

    MUX81 mux_4 (.D0(mdL0_0_4), .D1(mdL0_1_4), .D2(mdL0_2_4), .D3(mdL0_3_4), 
        .D4(mdL0_4_4), .D5(mdL0_5_4), .D6(mdL0_6_4), .D7(mdL0_7_4), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout4));

    MUX81 mux_3 (.D0(mdL0_0_3), .D1(mdL0_1_3), .D2(mdL0_2_3), .D3(mdL0_3_3), 
        .D4(mdL0_4_3), .D5(mdL0_5_3), .D6(mdL0_6_3), .D7(mdL0_7_3), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout3));

    MUX81 mux_2 (.D0(mdL0_0_2), .D1(mdL0_1_2), .D2(mdL0_2_2), .D3(mdL0_3_2), 
        .D4(mdL0_4_2), .D5(mdL0_5_2), .D6(mdL0_6_2), .D7(mdL0_7_2), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout2));

    MUX81 mux_1 (.D0(mdL0_0_1), .D1(mdL0_1_1), .D2(mdL0_2_1), .D3(mdL0_3_1), 
        .D4(mdL0_4_1), .D5(mdL0_5_1), .D6(mdL0_6_1), .D7(mdL0_7_1), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout1));

    MUX81 mux_0 (.D0(mdL0_0_0), .D1(mdL0_1_0), .D2(mdL0_2_0), .D3(mdL0_3_0), 
        .D4(mdL0_4_0), .D5(mdL0_5_0), .D6(mdL0_6_0), .D7(mdL0_7_0), .SD1(rptr_4), 
        .SD2(rptr_5), .SD3(rptr_6), .Z(rdataout0));

    defparam empty_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam empty_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam empty_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam empty_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), .B1(rden_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci));

    defparam empty_cmp_0.INJECT1_1 = "NO" ;
    defparam empty_cmp_0.INJECT1_0 = "NO" ;
    defparam empty_cmp_0.INIT1 =  16'h99AA ;
    defparam empty_cmp_0.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_0 (.A0(rcount_0), .A1(rcount_1), .B0(wcount_r0), .B1(wcount_r1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci), .S0(), .S1(), .COUT(co0_2));

    defparam empty_cmp_1.INJECT1_1 = "NO" ;
    defparam empty_cmp_1.INJECT1_0 = "NO" ;
    defparam empty_cmp_1.INIT1 =  16'h99AA ;
    defparam empty_cmp_1.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_1 (.A0(rcount_2), .A1(rcount_3), .B0(wcount_r2), .B1(wcount_r3), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_2), .S0(), .S1(), .COUT(co1_2));

    defparam empty_cmp_2.INJECT1_1 = "NO" ;
    defparam empty_cmp_2.INJECT1_0 = "NO" ;
    defparam empty_cmp_2.INIT1 =  16'h99AA ;
    defparam empty_cmp_2.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_2 (.A0(rcount_4), .A1(rcount_5), .B0(w_g2b_xor_cluster_0), 
        .B1(wcount_r5), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_2), .S0(), .S1(), .COUT(co2_2));

    defparam empty_cmp_3.INJECT1_1 = "NO" ;
    defparam empty_cmp_3.INJECT1_0 = "NO" ;
    defparam empty_cmp_3.INIT1 =  16'h99AA ;
    defparam empty_cmp_3.INIT0 =  16'h99AA ;
    CCU2C empty_cmp_3 (.A0(rcount_6), .A1(empty_cmp_set), .B0(wcount_r6), 
        .B1(empty_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_2), .S0(), .S1(), .COUT(empty_d_c));

    defparam a0.INJECT1_1 = "NO" ;
    defparam a0.INJECT1_0 = "NO" ;
    defparam a0.INIT1 =  16'h66AA ;
    defparam a0.INIT0 =  16'h66AA ;
    CCU2C a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(empty_d_c), .S0(empty_d), .S1(), .COUT());

    defparam full_cmp_ci_a.INJECT1_1 = "NO" ;
    defparam full_cmp_ci_a.INJECT1_0 = "NO" ;
    defparam full_cmp_ci_a.INIT1 =  16'h66AA ;
    defparam full_cmp_ci_a.INIT0 =  16'h66AA ;
    CCU2C full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(), .S0(), .S1(), .COUT(cmp_ci_1));

    defparam full_cmp_0.INJECT1_1 = "NO" ;
    defparam full_cmp_0.INJECT1_0 = "NO" ;
    defparam full_cmp_0.INIT1 =  16'h99AA ;
    defparam full_cmp_0.INIT0 =  16'h99AA ;
    CCU2C full_cmp_0 (.A0(wcount_0), .A1(wcount_1), .B0(rcount_w0), .B1(rcount_w1), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(cmp_ci_1), .S0(), .S1(), .COUT(co0_3));

    defparam full_cmp_1.INJECT1_1 = "NO" ;
    defparam full_cmp_1.INJECT1_0 = "NO" ;
    defparam full_cmp_1.INIT1 =  16'h99AA ;
    defparam full_cmp_1.INIT0 =  16'h99AA ;
    CCU2C full_cmp_1 (.A0(wcount_2), .A1(wcount_3), .B0(rcount_w2), .B1(rcount_w3), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0_3), .S0(), .S1(), .COUT(co1_3));

    defparam full_cmp_2.INJECT1_1 = "NO" ;
    defparam full_cmp_2.INJECT1_0 = "NO" ;
    defparam full_cmp_2.INIT1 =  16'h99AA ;
    defparam full_cmp_2.INIT0 =  16'h99AA ;
    CCU2C full_cmp_2 (.A0(wcount_4), .A1(wcount_5), .B0(r_g2b_xor_cluster_0), 
        .B1(rcount_w5), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co1_3), .S0(), .S1(), .COUT(co2_3));

    defparam full_cmp_3.INJECT1_1 = "NO" ;
    defparam full_cmp_3.INJECT1_0 = "NO" ;
    defparam full_cmp_3.INIT1 =  16'h99AA ;
    defparam full_cmp_3.INIT0 =  16'h99AA ;
    CCU2C full_cmp_3 (.A0(wcount_6), .A1(full_cmp_set), .B0(rcount_w6), 
        .B1(full_cmp_clr), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co2_3), .S0(), .S1(), .COUT(full_d_c));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam a1.INJECT1_1 = "NO" ;
    defparam a1.INJECT1_0 = "NO" ;
    defparam a1.INIT1 =  16'h66AA ;
    defparam a1.INIT0 =  16'h66AA ;
    CCU2C a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(full_d_c), .S0(full_d), .S1(), .COUT());

    defparam fifo_pfu_0_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_0_0 (.DI0(Data[8]), .DI1(Data[9]), .DI2(scuba_vhi), 
        .DI3(scuba_vhi), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), 
        .RAD1(rptr_1), .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), 
        .WAD2(wptr_2), .WAD3(wptr_3), .DO0(mdL0_0_8), .DO1(mdL0_0_9), .DO2(), 
        .DO3())
             /* synthesis MEM_INIT_FILE="(0-15)(0-3)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_0_0" */;

    defparam fifo_pfu_0_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_0_1 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_0_4), .DO1(mdL0_0_5), .DO2(mdL0_0_6), .DO3(mdL0_0_7))
             /* synthesis MEM_INIT_FILE="(0-15)(4-7)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_0_1" */;

    defparam fifo_pfu_0_2.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_0_2 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_0_0), .DO1(mdL0_0_1), .DO2(mdL0_0_2), .DO3(mdL0_0_3))
             /* synthesis MEM_INIT_FILE="(0-15)(8-9)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_0_2" */;

    defparam fifo_pfu_1_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_1_0 (.DI0(Data[8]), .DI1(Data[9]), .DI2(scuba_vhi), 
        .DI3(scuba_vhi), .WCK(WrClock), .WRE(dec1_wre7), .RAD0(rptr_0), 
        .RAD1(rptr_1), .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), 
        .WAD2(wptr_2), .WAD3(wptr_3), .DO0(mdL0_1_8), .DO1(mdL0_1_9), .DO2(), 
        .DO3())
             /* synthesis MEM_INIT_FILE="(16-31)(0-3)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_1_0" */;

    defparam fifo_pfu_1_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_1_1 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec1_wre7), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_1_4), .DO1(mdL0_1_5), .DO2(mdL0_1_6), .DO3(mdL0_1_7))
             /* synthesis MEM_INIT_FILE="(16-31)(4-7)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_1_1" */;

    defparam fifo_pfu_1_2.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_1_2 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec1_wre7), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_1_0), .DO1(mdL0_1_1), .DO2(mdL0_1_2), .DO3(mdL0_1_3))
             /* synthesis MEM_INIT_FILE="(16-31)(8-9)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_1_2" */;

    defparam fifo_pfu_2_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_2_0 (.DI0(Data[8]), .DI1(Data[9]), .DI2(scuba_vhi), 
        .DI3(scuba_vhi), .WCK(WrClock), .WRE(dec2_wre11), .RAD0(rptr_0), 
        .RAD1(rptr_1), .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), 
        .WAD2(wptr_2), .WAD3(wptr_3), .DO0(mdL0_2_8), .DO1(mdL0_2_9), .DO2(), 
        .DO3())
             /* synthesis MEM_INIT_FILE="(32-47)(0-3)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_2_0" */;

    defparam fifo_pfu_2_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_2_1 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec2_wre11), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_2_4), .DO1(mdL0_2_5), .DO2(mdL0_2_6), .DO3(mdL0_2_7))
             /* synthesis MEM_INIT_FILE="(32-47)(4-7)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_2_1" */;

    defparam fifo_pfu_2_2.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_2_2 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec2_wre11), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_2_0), .DO1(mdL0_2_1), .DO2(mdL0_2_2), .DO3(mdL0_2_3))
             /* synthesis MEM_INIT_FILE="(32-47)(8-9)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_2_2" */;

    defparam fifo_pfu_3_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_3_0 (.DI0(Data[8]), .DI1(Data[9]), .DI2(scuba_vhi), 
        .DI3(scuba_vhi), .WCK(WrClock), .WRE(dec3_wre15), .RAD0(rptr_0), 
        .RAD1(rptr_1), .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), 
        .WAD2(wptr_2), .WAD3(wptr_3), .DO0(mdL0_3_8), .DO1(mdL0_3_9), .DO2(), 
        .DO3())
             /* synthesis MEM_INIT_FILE="(48-63)(0-3)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_3_0" */;

    defparam fifo_pfu_3_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_3_1 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec3_wre15), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_3_4), .DO1(mdL0_3_5), .DO2(mdL0_3_6), .DO3(mdL0_3_7))
             /* synthesis MEM_INIT_FILE="(48-63)(4-7)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_3_1" */;

    defparam fifo_pfu_3_2.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_3_2 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec3_wre15), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_3_0), .DO1(mdL0_3_1), .DO2(mdL0_3_2), .DO3(mdL0_3_3))
             /* synthesis MEM_INIT_FILE="(48-63)(8-9)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_3_2" */;

    defparam fifo_pfu_4_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_4_0 (.DI0(Data[8]), .DI1(Data[9]), .DI2(scuba_vhi), 
        .DI3(scuba_vhi), .WCK(WrClock), .WRE(dec4_wre19), .RAD0(rptr_0), 
        .RAD1(rptr_1), .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), 
        .WAD2(wptr_2), .WAD3(wptr_3), .DO0(mdL0_4_8), .DO1(mdL0_4_9), .DO2(), 
        .DO3())
             /* synthesis MEM_INIT_FILE="(64-79)(0-3)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_4_0" */;

    defparam fifo_pfu_4_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_4_1 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec4_wre19), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_4_4), .DO1(mdL0_4_5), .DO2(mdL0_4_6), .DO3(mdL0_4_7))
             /* synthesis MEM_INIT_FILE="(64-79)(4-7)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_4_1" */;

    defparam fifo_pfu_4_2.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_4_2 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec4_wre19), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_4_0), .DO1(mdL0_4_1), .DO2(mdL0_4_2), .DO3(mdL0_4_3))
             /* synthesis MEM_INIT_FILE="(64-79)(8-9)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_4_2" */;

    defparam fifo_pfu_5_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_5_0 (.DI0(Data[8]), .DI1(Data[9]), .DI2(scuba_vhi), 
        .DI3(scuba_vhi), .WCK(WrClock), .WRE(dec5_wre23), .RAD0(rptr_0), 
        .RAD1(rptr_1), .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), 
        .WAD2(wptr_2), .WAD3(wptr_3), .DO0(mdL0_5_8), .DO1(mdL0_5_9), .DO2(), 
        .DO3())
             /* synthesis MEM_INIT_FILE="(80-95)(0-3)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_5_0" */;

    defparam fifo_pfu_5_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_5_1 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec5_wre23), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_5_4), .DO1(mdL0_5_5), .DO2(mdL0_5_6), .DO3(mdL0_5_7))
             /* synthesis MEM_INIT_FILE="(80-95)(4-7)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_5_1" */;

    defparam fifo_pfu_5_2.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_5_2 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec5_wre23), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_5_0), .DO1(mdL0_5_1), .DO2(mdL0_5_2), .DO3(mdL0_5_3))
             /* synthesis MEM_INIT_FILE="(80-95)(8-9)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_5_2" */;

    defparam fifo_pfu_6_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_6_0 (.DI0(Data[8]), .DI1(Data[9]), .DI2(scuba_vhi), 
        .DI3(scuba_vhi), .WCK(WrClock), .WRE(dec6_wre27), .RAD0(rptr_0), 
        .RAD1(rptr_1), .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), 
        .WAD2(wptr_2), .WAD3(wptr_3), .DO0(mdL0_6_8), .DO1(mdL0_6_9), .DO2(), 
        .DO3())
             /* synthesis MEM_INIT_FILE="(96-111)(0-3)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_6_0" */;

    defparam fifo_pfu_6_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_6_1 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec6_wre27), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_6_4), .DO1(mdL0_6_5), .DO2(mdL0_6_6), .DO3(mdL0_6_7))
             /* synthesis MEM_INIT_FILE="(96-111)(4-7)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_6_1" */;

    defparam fifo_pfu_6_2.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_6_2 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec6_wre27), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_6_0), .DO1(mdL0_6_1), .DO2(mdL0_6_2), .DO3(mdL0_6_3))
             /* synthesis MEM_INIT_FILE="(96-111)(8-9)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_6_2" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam fifo_pfu_7_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_7_0 (.DI0(Data[8]), .DI1(Data[9]), .DI2(scuba_vhi), 
        .DI3(scuba_vhi), .WCK(WrClock), .WRE(dec7_wre31), .RAD0(rptr_0), 
        .RAD1(rptr_1), .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), 
        .WAD2(wptr_2), .WAD3(wptr_3), .DO0(mdL0_7_8), .DO1(mdL0_7_9), .DO2(), 
        .DO3())
             /* synthesis MEM_INIT_FILE="(112-127)(0-3)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_7_0" */;

    defparam fifo_pfu_7_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_7_1 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec7_wre31), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_7_4), .DO1(mdL0_7_5), .DO2(mdL0_7_6), .DO3(mdL0_7_7))
             /* synthesis MEM_INIT_FILE="(112-127)(4-7)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_7_1" */;

    defparam fifo_pfu_7_2.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_7_2 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec7_wre31), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_7_0), .DO1(mdL0_7_1), .DO2(mdL0_7_2), .DO3(mdL0_7_3))
             /* synthesis MEM_INIT_FILE="(112-127)(8-9)" */
             /* synthesis MEM_LPC_FILE="asfifo_decode.lpc" */
             /* synthesis COMP="fifo_pfu_7_2" */;

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute FF_101 GSR ENABLED
    // exemplar attribute FF_100 GSR ENABLED
    // exemplar attribute FF_99 GSR ENABLED
    // exemplar attribute FF_98 GSR ENABLED
    // exemplar attribute FF_97 GSR ENABLED
    // exemplar attribute FF_96 GSR ENABLED
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute fifo_pfu_0_0 MEM_INIT_FILE (0-15)(0-3)
    // exemplar attribute fifo_pfu_0_0 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_0_0 COMP fifo_pfu_0_0
    // exemplar attribute fifo_pfu_0_1 MEM_INIT_FILE (0-15)(4-7)
    // exemplar attribute fifo_pfu_0_1 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_0_1 COMP fifo_pfu_0_1
    // exemplar attribute fifo_pfu_0_2 MEM_INIT_FILE (0-15)(8-9)
    // exemplar attribute fifo_pfu_0_2 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_0_2 COMP fifo_pfu_0_2
    // exemplar attribute fifo_pfu_1_0 MEM_INIT_FILE (16-31)(0-3)
    // exemplar attribute fifo_pfu_1_0 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_1_0 COMP fifo_pfu_1_0
    // exemplar attribute fifo_pfu_1_1 MEM_INIT_FILE (16-31)(4-7)
    // exemplar attribute fifo_pfu_1_1 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_1_1 COMP fifo_pfu_1_1
    // exemplar attribute fifo_pfu_1_2 MEM_INIT_FILE (16-31)(8-9)
    // exemplar attribute fifo_pfu_1_2 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_1_2 COMP fifo_pfu_1_2
    // exemplar attribute fifo_pfu_2_0 MEM_INIT_FILE (32-47)(0-3)
    // exemplar attribute fifo_pfu_2_0 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_2_0 COMP fifo_pfu_2_0
    // exemplar attribute fifo_pfu_2_1 MEM_INIT_FILE (32-47)(4-7)
    // exemplar attribute fifo_pfu_2_1 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_2_1 COMP fifo_pfu_2_1
    // exemplar attribute fifo_pfu_2_2 MEM_INIT_FILE (32-47)(8-9)
    // exemplar attribute fifo_pfu_2_2 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_2_2 COMP fifo_pfu_2_2
    // exemplar attribute fifo_pfu_3_0 MEM_INIT_FILE (48-63)(0-3)
    // exemplar attribute fifo_pfu_3_0 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_3_0 COMP fifo_pfu_3_0
    // exemplar attribute fifo_pfu_3_1 MEM_INIT_FILE (48-63)(4-7)
    // exemplar attribute fifo_pfu_3_1 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_3_1 COMP fifo_pfu_3_1
    // exemplar attribute fifo_pfu_3_2 MEM_INIT_FILE (48-63)(8-9)
    // exemplar attribute fifo_pfu_3_2 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_3_2 COMP fifo_pfu_3_2
    // exemplar attribute fifo_pfu_4_0 MEM_INIT_FILE (64-79)(0-3)
    // exemplar attribute fifo_pfu_4_0 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_4_0 COMP fifo_pfu_4_0
    // exemplar attribute fifo_pfu_4_1 MEM_INIT_FILE (64-79)(4-7)
    // exemplar attribute fifo_pfu_4_1 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_4_1 COMP fifo_pfu_4_1
    // exemplar attribute fifo_pfu_4_2 MEM_INIT_FILE (64-79)(8-9)
    // exemplar attribute fifo_pfu_4_2 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_4_2 COMP fifo_pfu_4_2
    // exemplar attribute fifo_pfu_5_0 MEM_INIT_FILE (80-95)(0-3)
    // exemplar attribute fifo_pfu_5_0 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_5_0 COMP fifo_pfu_5_0
    // exemplar attribute fifo_pfu_5_1 MEM_INIT_FILE (80-95)(4-7)
    // exemplar attribute fifo_pfu_5_1 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_5_1 COMP fifo_pfu_5_1
    // exemplar attribute fifo_pfu_5_2 MEM_INIT_FILE (80-95)(8-9)
    // exemplar attribute fifo_pfu_5_2 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_5_2 COMP fifo_pfu_5_2
    // exemplar attribute fifo_pfu_6_0 MEM_INIT_FILE (96-111)(0-3)
    // exemplar attribute fifo_pfu_6_0 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_6_0 COMP fifo_pfu_6_0
    // exemplar attribute fifo_pfu_6_1 MEM_INIT_FILE (96-111)(4-7)
    // exemplar attribute fifo_pfu_6_1 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_6_1 COMP fifo_pfu_6_1
    // exemplar attribute fifo_pfu_6_2 MEM_INIT_FILE (96-111)(8-9)
    // exemplar attribute fifo_pfu_6_2 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_6_2 COMP fifo_pfu_6_2
    // exemplar attribute fifo_pfu_7_0 MEM_INIT_FILE (112-127)(0-3)
    // exemplar attribute fifo_pfu_7_0 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_7_0 COMP fifo_pfu_7_0
    // exemplar attribute fifo_pfu_7_1 MEM_INIT_FILE (112-127)(4-7)
    // exemplar attribute fifo_pfu_7_1 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_7_1 COMP fifo_pfu_7_1
    // exemplar attribute fifo_pfu_7_2 MEM_INIT_FILE (112-127)(8-9)
    // exemplar attribute fifo_pfu_7_2 MEM_LPC_FILE asfifo_decode.lpc
    // exemplar attribute fifo_pfu_7_2 COMP fifo_pfu_7_2
    // exemplar end

endmodule
