/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 3.9 */
/* E:/tools/Iscc/diamond/3.12/ispfpga/bin/nt64/scuba -w -bus_exp 7 -bb -arch sa5p00 -type sdpram -num_rows 2 -data_width 2 -pipe_final_output -memformat bin -n pmi_distributed_dpramEbnoner2128cbfd2d -pmi -lang verilog  */
/* Sun May 23 18:37:22 2021 */


`timescale 1 ns / 1 ps
module pmi_distributed_dpramEbnoner2128cbfd2d (WrAddress, Data, WrClock, 
    WE, WrClockEn, RdAddress, RdClock, RdClockEn, Reset, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [0:0] WrAddress;
    input wire [1:0] Data;
    input wire WrClock;
    input wire WE;
    input wire WrClockEn;
    input wire [0:0] RdAddress;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    output wire [1:0] Q;

    wire dataout1_ffin;
    wire dataout0_ffin;
    wire dec0_wre3;
    wire scuba_vhi;

    defparam LUT4_0.initval =  16'h8000 ;
    ROM16X1A LUT4_0 (.AD3(WE), .AD2(WrClockEn), .AD1(scuba_vhi), .AD0(scuba_vhi), 
        .DO0(dec0_wre3));

    FD1P3DX FF_1 (.D(dataout1_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(dataout0_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam mem_0_0.initval = "0x0000000000000000" ;
    DPR16X4C mem_0_0 (.DI0(Data[0]), .DI1(Data[1]), .DI2(scuba_vhi), .DI3(scuba_vhi), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(scuba_vhi), 
        .RAD2(scuba_vhi), .RAD3(scuba_vhi), .WAD0(WrAddress[0]), .WAD1(scuba_vhi), 
        .WAD2(scuba_vhi), .WAD3(scuba_vhi), .DO0(dataout0_ffin), .DO1(dataout1_ffin), 
        .DO2(), .DO3())
             /* synthesis MEM_INIT_FILE="(0-1)(0-1)" */
             /* synthesis MEM_LPC_FILE="pmi_distributed_dpramEbnoner2128cbfd2d__PMI__2__2__2B" */
             /* synthesis COMP="mem_0_0" */;



    // exemplar begin
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_0 MEM_INIT_FILE (0-1)(0-1)
    // exemplar attribute mem_0_0 MEM_LPC_FILE pmi_distributed_dpramEbnoner2128cbfd2d__PMI__2__2__2B
    // exemplar attribute mem_0_0 COMP mem_0_0
    // exemplar end

endmodule
/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 6.5 */
/* E:/tools/Iscc/diamond/3.12/ispfpga/bin/nt64/scuba -w -bus_exp 7 -bb -arch sa5p00 -type bram -wp 10 -rp 0011 -data_width 1 -num_rows 65536 -rdata_width 1 -read_reg1 outreg -gsr DISABLED -reset_rel async -memformat bin -cascade -1 -n pmi_ram_dpEbnonesadr116655361166553612192a02 -pmi -lang verilog  */
/* Sun May 23 18:37:21 2021 */


`timescale 1 ns / 1 ps
module pmi_ram_dpEbnonesadr116655361166553612192a02 (WrAddress, 
    RdAddress, Data, WE, RdClock, RdClockEn, Reset, WrClock, WrClockEn, 
    Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] WrAddress;
    input wire [15:0] RdAddress;
    input wire [0:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [0:0] Q;

    wire scuba_vhi;
    wire raddr14_ff;
    wire scuba_vlo;
    wire raddr15_ff;
    wire raddr15_ff2;
    wire raddr14_ff2;
    wire mdout1_3_0;
    wire mdout1_2_0;
    wire mdout1_1_0;
    wire mdout1_0_0;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.GSR = "ENABLED" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.DATA_WIDTH_B = 1 ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3.DATA_WIDTH_A = 1 ;
    DP16KD pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3 (.DIA17(scuba_vlo), 
        .DIA16(scuba_vlo), .DIA15(scuba_vlo), .DIA14(scuba_vlo), .DIA13(scuba_vlo), 
        .DIA12(scuba_vlo), .DIA11(scuba_vlo), .DIA10(scuba_vlo), .DIA9(scuba_vlo), 
        .DIA8(scuba_vlo), .DIA7(scuba_vlo), .DIA6(scuba_vlo), .DIA5(scuba_vlo), 
        .DIA4(scuba_vlo), .DIA3(scuba_vlo), .DIA2(scuba_vlo), .DIA1(scuba_vlo), 
        .DIA0(Data[0]), .ADA13(WrAddress[13]), .ADA12(WrAddress[12]), .ADA11(WrAddress[11]), 
        .ADA10(WrAddress[10]), .ADA9(WrAddress[9]), .ADA8(WrAddress[8]), 
        .ADA7(WrAddress[7]), .ADA6(WrAddress[6]), .ADA5(WrAddress[5]), .ADA4(WrAddress[4]), 
        .ADA3(WrAddress[3]), .ADA2(WrAddress[2]), .ADA1(WrAddress[1]), .ADA0(WrAddress[0]), 
        .CEA(WrClockEn), .OCEA(WrClockEn), .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), 
        .CSA1(WrAddress[15]), .CSA0(WrAddress[14]), .RSTA(Reset), .DIB17(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB0(scuba_vlo), .ADB13(RdAddress[13]), .ADB12(RdAddress[12]), 
        .ADB11(RdAddress[11]), .ADB10(RdAddress[10]), .ADB9(RdAddress[9]), 
        .ADB8(RdAddress[8]), .ADB7(RdAddress[7]), .ADB6(RdAddress[6]), .ADB5(RdAddress[5]), 
        .ADB4(RdAddress[4]), .ADB3(RdAddress[3]), .ADB2(RdAddress[2]), .ADB1(RdAddress[1]), 
        .ADB0(RdAddress[0]), .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB2(scuba_vlo), .CSB1(RdAddress[15]), .CSB0(RdAddress[14]), 
        .RSTB(Reset), .DOA17(), .DOA16(), .DOA15(), .DOA14(), .DOA13(), 
        .DOA12(), .DOA11(), .DOA10(), .DOA9(), .DOA8(), .DOA7(), .DOA6(), 
        .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), .DOA0(), .DOB17(), 
        .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), .DOB11(), .DOB10(), 
        .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), .DOB4(), .DOB3(), .DOB2(), 
        .DOB1(), .DOB0(mdout1_0_0))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpEbnonesadr116655361166553612192a02__PMIP__65536__1__1B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.CSDECODE_B = "0b001" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.CSDECODE_A = "0b001" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.GSR = "ENABLED" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.DATA_WIDTH_B = 1 ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2.DATA_WIDTH_A = 1 ;
    DP16KD pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2 (.DIA17(scuba_vlo), 
        .DIA16(scuba_vlo), .DIA15(scuba_vlo), .DIA14(scuba_vlo), .DIA13(scuba_vlo), 
        .DIA12(scuba_vlo), .DIA11(scuba_vlo), .DIA10(scuba_vlo), .DIA9(scuba_vlo), 
        .DIA8(scuba_vlo), .DIA7(scuba_vlo), .DIA6(scuba_vlo), .DIA5(scuba_vlo), 
        .DIA4(scuba_vlo), .DIA3(scuba_vlo), .DIA2(scuba_vlo), .DIA1(scuba_vlo), 
        .DIA0(Data[0]), .ADA13(WrAddress[13]), .ADA12(WrAddress[12]), .ADA11(WrAddress[11]), 
        .ADA10(WrAddress[10]), .ADA9(WrAddress[9]), .ADA8(WrAddress[8]), 
        .ADA7(WrAddress[7]), .ADA6(WrAddress[6]), .ADA5(WrAddress[5]), .ADA4(WrAddress[4]), 
        .ADA3(WrAddress[3]), .ADA2(WrAddress[2]), .ADA1(WrAddress[1]), .ADA0(WrAddress[0]), 
        .CEA(WrClockEn), .OCEA(WrClockEn), .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), 
        .CSA1(WrAddress[15]), .CSA0(WrAddress[14]), .RSTA(Reset), .DIB17(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB0(scuba_vlo), .ADB13(RdAddress[13]), .ADB12(RdAddress[12]), 
        .ADB11(RdAddress[11]), .ADB10(RdAddress[10]), .ADB9(RdAddress[9]), 
        .ADB8(RdAddress[8]), .ADB7(RdAddress[7]), .ADB6(RdAddress[6]), .ADB5(RdAddress[5]), 
        .ADB4(RdAddress[4]), .ADB3(RdAddress[3]), .ADB2(RdAddress[2]), .ADB1(RdAddress[1]), 
        .ADB0(RdAddress[0]), .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB2(scuba_vlo), .CSB1(RdAddress[15]), .CSB0(RdAddress[14]), 
        .RSTB(Reset), .DOA17(), .DOA16(), .DOA15(), .DOA14(), .DOA13(), 
        .DOA12(), .DOA11(), .DOA10(), .DOA9(), .DOA8(), .DOA7(), .DOA6(), 
        .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), .DOA0(), .DOB17(), 
        .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), .DOB11(), .DOB10(), 
        .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), .DOB4(), .DOB3(), .DOB2(), 
        .DOB1(), .DOB0(mdout1_1_0))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpEbnonesadr116655361166553612192a02__PMIP__65536__1__1B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.CSDECODE_B = "0b010" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.CSDECODE_A = "0b010" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.GSR = "ENABLED" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.DATA_WIDTH_B = 1 ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1.DATA_WIDTH_A = 1 ;
    DP16KD pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1 (.DIA17(scuba_vlo), 
        .DIA16(scuba_vlo), .DIA15(scuba_vlo), .DIA14(scuba_vlo), .DIA13(scuba_vlo), 
        .DIA12(scuba_vlo), .DIA11(scuba_vlo), .DIA10(scuba_vlo), .DIA9(scuba_vlo), 
        .DIA8(scuba_vlo), .DIA7(scuba_vlo), .DIA6(scuba_vlo), .DIA5(scuba_vlo), 
        .DIA4(scuba_vlo), .DIA3(scuba_vlo), .DIA2(scuba_vlo), .DIA1(scuba_vlo), 
        .DIA0(Data[0]), .ADA13(WrAddress[13]), .ADA12(WrAddress[12]), .ADA11(WrAddress[11]), 
        .ADA10(WrAddress[10]), .ADA9(WrAddress[9]), .ADA8(WrAddress[8]), 
        .ADA7(WrAddress[7]), .ADA6(WrAddress[6]), .ADA5(WrAddress[5]), .ADA4(WrAddress[4]), 
        .ADA3(WrAddress[3]), .ADA2(WrAddress[2]), .ADA1(WrAddress[1]), .ADA0(WrAddress[0]), 
        .CEA(WrClockEn), .OCEA(WrClockEn), .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), 
        .CSA1(WrAddress[15]), .CSA0(WrAddress[14]), .RSTA(Reset), .DIB17(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB0(scuba_vlo), .ADB13(RdAddress[13]), .ADB12(RdAddress[12]), 
        .ADB11(RdAddress[11]), .ADB10(RdAddress[10]), .ADB9(RdAddress[9]), 
        .ADB8(RdAddress[8]), .ADB7(RdAddress[7]), .ADB6(RdAddress[6]), .ADB5(RdAddress[5]), 
        .ADB4(RdAddress[4]), .ADB3(RdAddress[3]), .ADB2(RdAddress[2]), .ADB1(RdAddress[1]), 
        .ADB0(RdAddress[0]), .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB2(scuba_vlo), .CSB1(RdAddress[15]), .CSB0(RdAddress[14]), 
        .RSTB(Reset), .DOA17(), .DOA16(), .DOA15(), .DOA14(), .DOA13(), 
        .DOA12(), .DOA11(), .DOA10(), .DOA9(), .DOA8(), .DOA7(), .DOA6(), 
        .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), .DOA0(), .DOB17(), 
        .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), .DOB11(), .DOB10(), 
        .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), .DOB4(), .DOB3(), .DOB2(), 
        .DOB1(), .DOB0(mdout1_2_0))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpEbnonesadr116655361166553612192a02__PMIP__65536__1__1B" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.CSDECODE_B = "0b011" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.CSDECODE_A = "0b011" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.GSR = "ENABLED" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.DATA_WIDTH_B = 1 ;
    defparam pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0.DATA_WIDTH_A = 1 ;
    DP16KD pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0 (.DIA17(scuba_vlo), 
        .DIA16(scuba_vlo), .DIA15(scuba_vlo), .DIA14(scuba_vlo), .DIA13(scuba_vlo), 
        .DIA12(scuba_vlo), .DIA11(scuba_vlo), .DIA10(scuba_vlo), .DIA9(scuba_vlo), 
        .DIA8(scuba_vlo), .DIA7(scuba_vlo), .DIA6(scuba_vlo), .DIA5(scuba_vlo), 
        .DIA4(scuba_vlo), .DIA3(scuba_vlo), .DIA2(scuba_vlo), .DIA1(scuba_vlo), 
        .DIA0(Data[0]), .ADA13(WrAddress[13]), .ADA12(WrAddress[12]), .ADA11(WrAddress[11]), 
        .ADA10(WrAddress[10]), .ADA9(WrAddress[9]), .ADA8(WrAddress[8]), 
        .ADA7(WrAddress[7]), .ADA6(WrAddress[6]), .ADA5(WrAddress[5]), .ADA4(WrAddress[4]), 
        .ADA3(WrAddress[3]), .ADA2(WrAddress[2]), .ADA1(WrAddress[1]), .ADA0(WrAddress[0]), 
        .CEA(WrClockEn), .OCEA(WrClockEn), .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), 
        .CSA1(WrAddress[15]), .CSA0(WrAddress[14]), .RSTA(Reset), .DIB17(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB0(scuba_vlo), .ADB13(RdAddress[13]), .ADB12(RdAddress[12]), 
        .ADB11(RdAddress[11]), .ADB10(RdAddress[10]), .ADB9(RdAddress[9]), 
        .ADB8(RdAddress[8]), .ADB7(RdAddress[7]), .ADB6(RdAddress[6]), .ADB5(RdAddress[5]), 
        .ADB4(RdAddress[4]), .ADB3(RdAddress[3]), .ADB2(RdAddress[2]), .ADB1(RdAddress[1]), 
        .ADB0(RdAddress[0]), .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), 
        .WEB(scuba_vlo), .CSB2(scuba_vlo), .CSB1(RdAddress[15]), .CSB0(RdAddress[14]), 
        .RSTB(Reset), .DOA17(), .DOA16(), .DOA15(), .DOA14(), .DOA13(), 
        .DOA12(), .DOA11(), .DOA10(), .DOA9(), .DOA8(), .DOA7(), .DOA6(), 
        .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(), .DOA0(), .DOB17(), 
        .DOB16(), .DOB15(), .DOB14(), .DOB13(), .DOB12(), .DOB11(), .DOB10(), 
        .DOB9(), .DOB8(), .DOB7(), .DOB6(), .DOB5(), .DOB4(), .DOB3(), .DOB2(), 
        .DOB1(), .DOB0(mdout1_3_0))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpEbnonesadr116655361166553612192a02__PMIP__65536__1__1B" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3DX FF_3 (.D(RdAddress[14]), .SP(RdClockEn), .CK(RdClock), .CD(scuba_vlo), 
        .Q(raddr14_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(RdAddress[15]), .SP(RdClockEn), .CK(RdClock), .CD(scuba_vlo), 
        .Q(raddr15_ff))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(raddr14_ff), .SP(RdClockEn), .CK(RdClock), .CD(scuba_vlo), 
        .Q(raddr14_ff2))
             /* synthesis GSR="ENABLED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FD1P3DX FF_0 (.D(raddr15_ff), .SP(RdClockEn), .CK(RdClock), .CD(scuba_vlo), 
        .Q(raddr15_ff2))
             /* synthesis GSR="ENABLED" */;

    MUX41 mux_0 (.D0(mdout1_0_0), .D1(mdout1_1_0), .D2(mdout1_2_0), .D3(mdout1_3_0), 
        .SD1(raddr14_ff2), .SD2(raddr15_ff2), .Z(Q[0]));



    // exemplar begin
    // exemplar attribute pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3 MEM_LPC_FILE pmi_ram_dpEbnonesadr116655361166553612192a02__PMIP__65536__1__1B
    // exemplar attribute pmi_ram_dpEbnonesadr116655361166553612192a02_0_0_3 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2 MEM_LPC_FILE pmi_ram_dpEbnonesadr116655361166553612192a02__PMIP__65536__1__1B
    // exemplar attribute pmi_ram_dpEbnonesadr116655361166553612192a02_1_0_2 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1 MEM_LPC_FILE pmi_ram_dpEbnonesadr116655361166553612192a02__PMIP__65536__1__1B
    // exemplar attribute pmi_ram_dpEbnonesadr116655361166553612192a02_2_0_1 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0 MEM_LPC_FILE pmi_ram_dpEbnonesadr116655361166553612192a02__PMIP__65536__1__1B
    // exemplar attribute pmi_ram_dpEbnonesadr116655361166553612192a02_3_0_0 MEM_INIT_FILE 
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
