/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 6.5 */
/* D:/LATTICE/diamond/3.12/ispfpga/bin/nt64/scuba -w -bus_exp 7 -bb -arch sa5p00 -type bram -wp 10 -rp 0011 -data_width 33 -num_rows 1024 -rdata_width 33 -read_reg1 outreg -gsr DISABLED -reset_rel async -memformat bin -cascade -1 -n pmi_ram_dpEbnonesadr3310102433101024121889e0 -pmi -lang verilog  */
/* Fri Jan 28 11:23:39 2022 */


`timescale 1 ns / 1 ps
module pmi_ram_dpEbnonesadr3310102433101024121889e0 (WrAddress, 
    RdAddress, Data, WE, RdClock, RdClockEn, Reset, WrClock, WrClockEn, 
    Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [9:0] WrAddress;
    input wire [9:0] RdAddress;
    input wire [32:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [32:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.GSR = "ENABLED" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.DATA_WIDTH_B = 18 ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1.DATA_WIDTH_A = 18 ;
    DP16KD pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1 (.DIA17(Data[17]), 
        .DIA16(Data[16]), .DIA15(Data[15]), .DIA14(Data[14]), .DIA13(Data[13]), 
        .DIA12(Data[12]), .DIA11(Data[11]), .DIA10(Data[10]), .DIA9(Data[9]), 
        .DIA8(Data[8]), .DIA7(Data[7]), .DIA6(Data[6]), .DIA5(Data[5]), 
        .DIA4(Data[4]), .DIA3(Data[3]), .DIA2(Data[2]), .DIA1(Data[1]), 
        .DIA0(Data[0]), .ADA13(WrAddress[9]), .ADA12(WrAddress[8]), .ADA11(WrAddress[7]), 
        .ADA10(WrAddress[6]), .ADA9(WrAddress[5]), .ADA8(WrAddress[4]), 
        .ADA7(WrAddress[3]), .ADA6(WrAddress[2]), .ADA5(WrAddress[1]), .ADA4(WrAddress[0]), 
        .ADA3(scuba_vlo), .ADA2(scuba_vlo), .ADA1(scuba_vhi), .ADA0(scuba_vhi), 
        .CEA(WrClockEn), .OCEA(WrClockEn), .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), 
        .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), .DIB17(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB0(scuba_vlo), .ADB13(RdAddress[9]), .ADB12(RdAddress[8]), .ADB11(RdAddress[7]), 
        .ADB10(RdAddress[6]), .ADB9(RdAddress[5]), .ADB8(RdAddress[4]), 
        .ADB7(RdAddress[3]), .ADB6(RdAddress[2]), .ADB5(RdAddress[1]), .ADB4(RdAddress[0]), 
        .ADB3(scuba_vlo), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA17(), .DOA16(), .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), 
        .DOA10(), .DOA9(), .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), 
        .DOA3(), .DOA2(), .DOA1(), .DOA0(), .DOB17(Q[17]), .DOB16(Q[16]), 
        .DOB15(Q[15]), .DOB14(Q[14]), .DOB13(Q[13]), .DOB12(Q[12]), .DOB11(Q[11]), 
        .DOB10(Q[10]), .DOB9(Q[9]), .DOB8(Q[8]), .DOB7(Q[7]), .DOB6(Q[6]), 
        .DOB5(Q[5]), .DOB4(Q[4]), .DOB3(Q[3]), .DOB2(Q[2]), .DOB1(Q[1]), 
        .DOB0(Q[0]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpEbnonesadr3310102433101024121889e0__PMIP__1024__33__33B" */
             /* synthesis MEM_INIT_FILE="" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.INIT_DATA = "STATIC" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.CSDECODE_B = "0b000" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.CSDECODE_A = "0b000" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.WRITEMODE_B = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.WRITEMODE_A = "NORMAL" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.GSR = "ENABLED" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.RESETMODE = "ASYNC" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.REGMODE_B = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.REGMODE_A = "OUTREG" ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.DATA_WIDTH_B = 18 ;
    defparam pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0.DATA_WIDTH_A = 18 ;
    DP16KD pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0 (.DIA17(scuba_vlo), 
        .DIA16(scuba_vlo), .DIA15(scuba_vlo), .DIA14(Data[32]), .DIA13(Data[31]), 
        .DIA12(Data[30]), .DIA11(Data[29]), .DIA10(Data[28]), .DIA9(Data[27]), 
        .DIA8(Data[26]), .DIA7(Data[25]), .DIA6(Data[24]), .DIA5(Data[23]), 
        .DIA4(Data[22]), .DIA3(Data[21]), .DIA2(Data[20]), .DIA1(Data[19]), 
        .DIA0(Data[18]), .ADA13(WrAddress[9]), .ADA12(WrAddress[8]), .ADA11(WrAddress[7]), 
        .ADA10(WrAddress[6]), .ADA9(WrAddress[5]), .ADA8(WrAddress[4]), 
        .ADA7(WrAddress[3]), .ADA6(WrAddress[2]), .ADA5(WrAddress[1]), .ADA4(WrAddress[0]), 
        .ADA3(scuba_vlo), .ADA2(scuba_vlo), .ADA1(scuba_vhi), .ADA0(scuba_vhi), 
        .CEA(WrClockEn), .OCEA(WrClockEn), .CLKA(WrClock), .WEA(WE), .CSA2(scuba_vlo), 
        .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), .DIB17(scuba_vlo), 
        .DIB16(scuba_vlo), .DIB15(scuba_vlo), .DIB14(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB12(scuba_vlo), .DIB11(scuba_vlo), .DIB10(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB0(scuba_vlo), .ADB13(RdAddress[9]), .ADB12(RdAddress[8]), .ADB11(RdAddress[7]), 
        .ADB10(RdAddress[6]), .ADB9(RdAddress[5]), .ADB8(RdAddress[4]), 
        .ADB7(RdAddress[3]), .ADB6(RdAddress[2]), .ADB5(RdAddress[1]), .ADB4(RdAddress[0]), 
        .ADB3(scuba_vlo), .ADB2(scuba_vlo), .ADB1(scuba_vlo), .ADB0(scuba_vlo), 
        .CEB(RdClockEn), .OCEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), 
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset), 
        .DOA17(), .DOA16(), .DOA15(), .DOA14(), .DOA13(), .DOA12(), .DOA11(), 
        .DOA10(), .DOA9(), .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), 
        .DOA3(), .DOA2(), .DOA1(), .DOA0(), .DOB17(), .DOB16(), .DOB15(), 
        .DOB14(Q[32]), .DOB13(Q[31]), .DOB12(Q[30]), .DOB11(Q[29]), .DOB10(Q[28]), 
        .DOB9(Q[27]), .DOB8(Q[26]), .DOB7(Q[25]), .DOB6(Q[24]), .DOB5(Q[23]), 
        .DOB4(Q[22]), .DOB3(Q[21]), .DOB2(Q[20]), .DOB1(Q[19]), .DOB0(Q[18]))
             /* synthesis MEM_LPC_FILE="pmi_ram_dpEbnonesadr3310102433101024121889e0__PMIP__1024__33__33B" */
             /* synthesis MEM_INIT_FILE="" */;



    // exemplar begin
    // exemplar attribute pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1 MEM_LPC_FILE pmi_ram_dpEbnonesadr3310102433101024121889e0__PMIP__1024__33__33B
    // exemplar attribute pmi_ram_dpEbnonesadr3310102433101024121889e0_0_0_1 MEM_INIT_FILE 
    // exemplar attribute pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0 MEM_LPC_FILE pmi_ram_dpEbnonesadr3310102433101024121889e0__PMIP__1024__33__33B
    // exemplar attribute pmi_ram_dpEbnonesadr3310102433101024121889e0_0_1_0 MEM_INIT_FILE 
    // exemplar end

endmodule
