[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 17;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = u_eth_top/u_eth_pll/CLKOP;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 1;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = u_ddr3/ddr3_ipcore_inst/U1_clocking/clkop;
GLOBAL_PRIMARY_1_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_1_LOADNUM = 1;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = w_pll_50m;
GLOBAL_PRIMARY_2_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_2_LOADNUM = 879;
; Global primary clock #3
GLOBAL_PRIMARY_3_SIGNALNAME = jtaghub16_jtck;
GLOBAL_PRIMARY_3_DRIVERTYPE = JTAG;
GLOBAL_PRIMARY_3_LOADNUM = 448;
; Global primary clock #4
GLOBAL_PRIMARY_4_SIGNALNAME = w_pll_100m;
GLOBAL_PRIMARY_4_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_4_LOADNUM = 4090;
; Global primary clock #5
GLOBAL_PRIMARY_5_SIGNALNAME = w_sclk;
GLOBAL_PRIMARY_5_DRIVERTYPE = CLKDIV;
GLOBAL_PRIMARY_5_LOADNUM = 1677;
; Global primary clock #6
GLOBAL_PRIMARY_6_SIGNALNAME = w_iddr_sclk2;
GLOBAL_PRIMARY_6_DRIVERTYPE = CLKDIV;
GLOBAL_PRIMARY_6_LOADNUM = 120;
; Global primary clock #7
GLOBAL_PRIMARY_7_SIGNALNAME = w_iddr_sclk1;
GLOBAL_PRIMARY_7_DRIVERTYPE = CLKDIV;
GLOBAL_PRIMARY_7_LOADNUM = 120;
; Global primary clock #8
GLOBAL_PRIMARY_8_SIGNALNAME = u_eth_top.w_ethphy_refclk_90;
GLOBAL_PRIMARY_8_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_8_LOADNUM = 41;
; Global primary clock #9
GLOBAL_PRIMARY_9_SIGNALNAME = u_ddr3/ddr3_ipcore_inst/U1_clocking/clkos;
GLOBAL_PRIMARY_9_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_9_LOADNUM = 12;
; Global primary clock #10
GLOBAL_PRIMARY_10_SIGNALNAME = w_pll_150m;
GLOBAL_PRIMARY_10_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_10_LOADNUM = 58;
; Global primary clock #11
GLOBAL_PRIMARY_11_SIGNALNAME = i_ethphy_refclk_c;
GLOBAL_PRIMARY_11_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_11_LOADNUM = 21;
; Global primary clock #12
GLOBAL_PRIMARY_12_SIGNALNAME = i_clk_50m_c;
GLOBAL_PRIMARY_12_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_12_LOADNUM = 16;
; Global primary clock #13
GLOBAL_PRIMARY_13_SIGNALNAME = r_ddrrst_n;
GLOBAL_PRIMARY_13_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_13_LOADNUM = 0;
; Global primary clock #14
GLOBAL_PRIMARY_14_SIGNALNAME = r2_150mrst_sync;
GLOBAL_PRIMARY_14_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_14_LOADNUM = 0;
; Global primary clock #15
GLOBAL_PRIMARY_15_SIGNALNAME = jtaghub16_jrstn;
GLOBAL_PRIMARY_15_DRIVERTYPE = JTAG;
GLOBAL_PRIMARY_15_LOADNUM = 0;
; Global primary clock #16
GLOBAL_PRIMARY_16_SIGNALNAME = u_ddr3/ddr3_ipcore_inst/U1_clocking/clk_in_c;
GLOBAL_PRIMARY_16_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_16_LOADNUM = 1;
; I/O Bank 0 Usage
BANK_0_USED = 11;
BANK_0_AVAIL = 24;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
BANK_0_VREF2 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 18;
BANK_1_AVAIL = 32;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
BANK_1_VREF2 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 9;
BANK_2_AVAIL = 32;
BANK_2_VCCIO = 2.5V;
BANK_2_VREF1 = NA;
BANK_2_VREF2 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 16;
BANK_3_AVAIL = 32;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
BANK_3_VREF2 = NA;
; I/O Bank 6 Usage
BANK_6_USED = 25;
BANK_6_AVAIL = 32;
BANK_6_VCCIO = 1.35V;
BANK_6_VREF1 = 0.675V@VREF1;
BANK_6_VREF2 = NA;
; I/O Bank 7 Usage
BANK_7_USED = 26;
BANK_7_AVAIL = 32;
BANK_7_VCCIO = 1.35V;
BANK_7_VREF1 = NA;
BANK_7_VREF2 = NA;
; I/O Bank 8 Usage
BANK_8_USED = 5;
BANK_8_AVAIL = 13;
BANK_8_VCCIO = 2.5V;
BANK_8_VREF1 = NA;
BANK_8_VREF2 = NA;
