/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.4 */
/* Wed May 21 20:01:02 2025 */

/* parameterized module instance */
mpt2042_rom __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), 
    .Q( ));
