/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.1 */
/* Thu Sep 02 13:46:49 2021 */

/* parameterized module instance */
tcp_recv_fifo __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), 
    .Q( ), .WCNT( ), .Empty( ), .Full( ));
