/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.4 */
/* Tue Jun 03 17:12:51 2025 */

/* parameterized module instance */
mpt2042_rom_128x8 __ (.Address( ), .OutClock( ), .OutClockEn( ), 
    .Reset( ), .Q( ));
