/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.1 */
/* Wed May 19 16:28:06 2021 */

/* parameterized module instance */
eth_data_fifo __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), 
    .Q( ), .WCNT( ), .Empty( ), .Full( ));
