/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 5.7 */
/* Sat Mar 29 16:30:19 2025 */

/* parameterized module instance */
c25x_pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ));
