/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.1 */
/* Wed Feb 26 13:50:45 2025 */

/* parameterized module instance */
sfifo_64x48 __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), 
    .Q( ), .Empty( ), .Full( ));
