/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 4.9 */
/* Thu May 15 16:48:31 2025 */

/* parameterized module instance */
multiplier_10x32 __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), 
    .DataB( ), .Result( ));
