/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.0.240.2 */
/* Module Version: 4.9 */
/* Thu Sep 02 13:44:32 2021 */

/* parameterized module instance */
multiplier3 __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), .DataB( ), 
    .Result( ));
