/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.8 */
/* Fri Oct 18 15:16:14 2024 */

/* parameterized module instance */
dcfifo_rmiirx_36x2 __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), 
    .RdEn( ), .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ));
