/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 4.9 */
/* D:\TOOL\LatticeDiamond\diamond\3.13\ispfpga\bin\nt64\scuba.exe -w -n multiplier_in32bit -lang verilog -synth synplify -bus_exp 7 -bb -arch sa5p00 -type dspmult -simple_portname -widtha 10 -widthb 32 -widthp 42 -PL_stages 1 -output_reg -clk0 -ce0 -rst0 -fdc D:/FreeWork/df1_demo/df1_lidar_top/src/ip/df1_lidar_ip/multiplier_in32bit/multiplier_in32bit.fdc  */
/* Thu Dec 19 11:41:06 2024 */


`timescale 1 ns / 1 ps
module multiplier_in32bit (Clock, ClkEn, Aclr, DataA, DataB, Result)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Aclr;
    input wire [9:0] DataA;
    input wire [31:0] DataB;
    output wire [41:0] Result;

    wire multiplier_in32bit_alu_signedr_1_0;
    wire multiplier_in32bit_alu_output_r_1_0_53;
    wire multiplier_in32bit_alu_output_r_1_0_52;
    wire multiplier_in32bit_alu_output_r_1_0_51;
    wire multiplier_in32bit_alu_output_r_1_0_50;
    wire multiplier_in32bit_alu_output_r_1_0_49;
    wire multiplier_in32bit_alu_output_r_1_0_48;
    wire multiplier_in32bit_alu_output_r_1_0_47;
    wire multiplier_in32bit_alu_output_r_1_0_46;
    wire multiplier_in32bit_alu_output_r_1_0_45;
    wire multiplier_in32bit_alu_output_r_1_0_44;
    wire multiplier_in32bit_alu_output_r_1_0_43;
    wire multiplier_in32bit_alu_output_r_1_0_42;
    wire multiplier_in32bit_alu_output_r_1_0_41;
    wire multiplier_in32bit_alu_output_r_1_0_40;
    wire multiplier_in32bit_alu_output_r_1_0_39;
    wire multiplier_in32bit_alu_output_r_1_0_38;
    wire multiplier_in32bit_alu_output_r_1_0_37;
    wire multiplier_in32bit_alu_output_r_1_0_36;
    wire multiplier_in32bit_alu_output_r_1_0_35;
    wire multiplier_in32bit_alu_output_r_1_0_34;
    wire multiplier_in32bit_alu_output_r_1_0_33;
    wire multiplier_in32bit_alu_output_r_1_0_32;
    wire multiplier_in32bit_alu_output_r_1_0_31;
    wire multiplier_in32bit_alu_output_r_1_0_30;
    wire multiplier_in32bit_alu_output_r_1_0_29;
    wire multiplier_in32bit_alu_output_r_1_0_28;
    wire multiplier_in32bit_alu_output_r_1_0_27;
    wire multiplier_in32bit_alu_output_r_1_0_26;
    wire multiplier_in32bit_alu_output_r_1_0_25;
    wire multiplier_in32bit_alu_output_r_1_0_24;
    wire multiplier_in32bit_alu_output_r_1_0_23;
    wire multiplier_in32bit_alu_output_r_1_0_22;
    wire multiplier_in32bit_alu_output_r_1_0_21;
    wire multiplier_in32bit_alu_output_r_1_0_20;
    wire multiplier_in32bit_alu_output_r_1_0_19;
    wire multiplier_in32bit_alu_output_r_1_0_18;
    wire multiplier_in32bit_alu_output_r_1_0_17;
    wire multiplier_in32bit_alu_output_r_1_0_16;
    wire multiplier_in32bit_alu_output_r_1_0_15;
    wire multiplier_in32bit_alu_output_r_1_0_14;
    wire multiplier_in32bit_alu_output_r_1_0_13;
    wire multiplier_in32bit_alu_output_r_1_0_12;
    wire multiplier_in32bit_alu_output_r_1_0_11;
    wire multiplier_in32bit_alu_output_r_1_0_10;
    wire multiplier_in32bit_alu_output_r_1_0_9;
    wire multiplier_in32bit_alu_output_r_1_0_8;
    wire multiplier_in32bit_alu_output_r_1_0_7;
    wire multiplier_in32bit_alu_output_r_1_0_6;
    wire multiplier_in32bit_alu_output_r_1_0_5;
    wire multiplier_in32bit_alu_output_r_1_0_4;
    wire multiplier_in32bit_alu_output_r_1_0_3;
    wire multiplier_in32bit_alu_output_r_1_0_2;
    wire multiplier_in32bit_alu_output_r_1_0_1;
    wire multiplier_in32bit_alu_output_r_1_0_0;
    wire multiplier_in32bit_alu_signedcin_1_0;
    wire multiplier_in32bit_alu_in_cin_1_0_53;
    wire multiplier_in32bit_alu_in_cin_1_0_52;
    wire multiplier_in32bit_alu_in_cin_1_0_51;
    wire multiplier_in32bit_alu_in_cin_1_0_50;
    wire multiplier_in32bit_alu_in_cin_1_0_49;
    wire multiplier_in32bit_alu_in_cin_1_0_48;
    wire multiplier_in32bit_alu_in_cin_1_0_47;
    wire multiplier_in32bit_alu_in_cin_1_0_46;
    wire multiplier_in32bit_alu_in_cin_1_0_45;
    wire multiplier_in32bit_alu_in_cin_1_0_44;
    wire multiplier_in32bit_alu_in_cin_1_0_43;
    wire multiplier_in32bit_alu_in_cin_1_0_42;
    wire multiplier_in32bit_alu_in_cin_1_0_41;
    wire multiplier_in32bit_alu_in_cin_1_0_40;
    wire multiplier_in32bit_alu_in_cin_1_0_39;
    wire multiplier_in32bit_alu_in_cin_1_0_38;
    wire multiplier_in32bit_alu_in_cin_1_0_37;
    wire multiplier_in32bit_alu_in_cin_1_0_36;
    wire multiplier_in32bit_alu_in_cin_1_0_35;
    wire multiplier_in32bit_alu_in_cin_1_0_34;
    wire multiplier_in32bit_alu_in_cin_1_0_33;
    wire multiplier_in32bit_alu_in_cin_1_0_32;
    wire multiplier_in32bit_alu_in_cin_1_0_31;
    wire multiplier_in32bit_alu_in_cin_1_0_30;
    wire multiplier_in32bit_alu_in_cin_1_0_29;
    wire multiplier_in32bit_alu_in_cin_1_0_28;
    wire multiplier_in32bit_alu_in_cin_1_0_27;
    wire multiplier_in32bit_alu_in_cin_1_0_26;
    wire multiplier_in32bit_alu_in_cin_1_0_25;
    wire multiplier_in32bit_alu_in_cin_1_0_24;
    wire multiplier_in32bit_alu_in_cin_1_0_23;
    wire multiplier_in32bit_alu_in_cin_1_0_22;
    wire multiplier_in32bit_alu_in_cin_1_0_21;
    wire multiplier_in32bit_alu_in_cin_1_0_20;
    wire multiplier_in32bit_alu_in_cin_1_0_19;
    wire multiplier_in32bit_alu_in_cin_1_0_18;
    wire multiplier_in32bit_alu_in_cin_1_0_17;
    wire multiplier_in32bit_alu_in_cin_1_0_16;
    wire multiplier_in32bit_alu_in_cin_1_0_15;
    wire multiplier_in32bit_alu_in_cin_1_0_14;
    wire multiplier_in32bit_alu_in_cin_1_0_13;
    wire multiplier_in32bit_alu_in_cin_1_0_12;
    wire multiplier_in32bit_alu_in_cin_1_0_11;
    wire multiplier_in32bit_alu_in_cin_1_0_10;
    wire multiplier_in32bit_alu_in_cin_1_0_9;
    wire multiplier_in32bit_alu_in_cin_1_0_8;
    wire multiplier_in32bit_alu_in_cin_1_0_7;
    wire multiplier_in32bit_alu_in_cin_1_0_6;
    wire multiplier_in32bit_alu_in_cin_1_0_5;
    wire multiplier_in32bit_alu_in_cin_1_0_4;
    wire multiplier_in32bit_alu_in_cin_1_0_3;
    wire multiplier_in32bit_alu_in_cin_1_0_2;
    wire multiplier_in32bit_alu_in_cin_1_0_1;
    wire multiplier_in32bit_alu_in_cin_1_0_0;
    wire multiplier_in32bit_mult_out_rob_0_17;
    wire multiplier_in32bit_mult_out_roa_0_17;
    wire multiplier_in32bit_mult_out_rob_0_16;
    wire multiplier_in32bit_mult_out_roa_0_16;
    wire multiplier_in32bit_mult_out_rob_0_15;
    wire multiplier_in32bit_mult_out_roa_0_15;
    wire multiplier_in32bit_mult_out_rob_0_14;
    wire multiplier_in32bit_mult_out_roa_0_14;
    wire multiplier_in32bit_mult_out_rob_0_13;
    wire multiplier_in32bit_mult_out_roa_0_13;
    wire multiplier_in32bit_mult_out_rob_0_12;
    wire multiplier_in32bit_mult_out_roa_0_12;
    wire multiplier_in32bit_mult_out_rob_0_11;
    wire multiplier_in32bit_mult_out_roa_0_11;
    wire multiplier_in32bit_mult_out_rob_0_10;
    wire multiplier_in32bit_mult_out_roa_0_10;
    wire multiplier_in32bit_mult_out_rob_0_9;
    wire multiplier_in32bit_mult_out_roa_0_9;
    wire multiplier_in32bit_mult_out_rob_0_8;
    wire multiplier_in32bit_mult_out_roa_0_8;
    wire multiplier_in32bit_mult_out_rob_0_7;
    wire multiplier_in32bit_mult_out_roa_0_7;
    wire multiplier_in32bit_mult_out_rob_0_6;
    wire multiplier_in32bit_mult_out_roa_0_6;
    wire multiplier_in32bit_mult_out_rob_0_5;
    wire multiplier_in32bit_mult_out_roa_0_5;
    wire multiplier_in32bit_mult_out_rob_0_4;
    wire multiplier_in32bit_mult_out_roa_0_4;
    wire multiplier_in32bit_mult_out_rob_0_3;
    wire multiplier_in32bit_mult_out_roa_0_3;
    wire multiplier_in32bit_mult_out_rob_0_2;
    wire multiplier_in32bit_mult_out_roa_0_2;
    wire multiplier_in32bit_mult_out_rob_0_1;
    wire multiplier_in32bit_mult_out_roa_0_1;
    wire multiplier_in32bit_mult_out_rob_0_0;
    wire multiplier_in32bit_mult_out_roa_0_0;
    wire multiplier_in32bit_mult_out_p_0_35;
    wire multiplier_in32bit_mult_out_p_0_34;
    wire multiplier_in32bit_mult_out_p_0_33;
    wire multiplier_in32bit_mult_out_p_0_32;
    wire multiplier_in32bit_mult_out_p_0_31;
    wire multiplier_in32bit_mult_out_p_0_30;
    wire multiplier_in32bit_mult_out_p_0_29;
    wire multiplier_in32bit_mult_out_p_0_28;
    wire multiplier_in32bit_mult_out_p_0_27;
    wire multiplier_in32bit_mult_out_p_0_26;
    wire multiplier_in32bit_mult_out_p_0_25;
    wire multiplier_in32bit_mult_out_p_0_24;
    wire multiplier_in32bit_mult_out_p_0_23;
    wire multiplier_in32bit_mult_out_p_0_22;
    wire multiplier_in32bit_mult_out_p_0_21;
    wire multiplier_in32bit_mult_out_p_0_20;
    wire multiplier_in32bit_mult_out_p_0_19;
    wire multiplier_in32bit_mult_out_p_0_18;
    wire multiplier_in32bit_mult_out_p_0_17;
    wire multiplier_in32bit_mult_out_p_0_16;
    wire multiplier_in32bit_mult_out_p_0_15;
    wire multiplier_in32bit_mult_out_p_0_14;
    wire multiplier_in32bit_mult_out_p_0_13;
    wire multiplier_in32bit_mult_out_p_0_12;
    wire multiplier_in32bit_mult_out_p_0_11;
    wire multiplier_in32bit_mult_out_p_0_10;
    wire multiplier_in32bit_mult_out_p_0_9;
    wire multiplier_in32bit_mult_out_p_0_8;
    wire multiplier_in32bit_mult_out_p_0_7;
    wire multiplier_in32bit_mult_out_p_0_6;
    wire multiplier_in32bit_mult_out_p_0_5;
    wire multiplier_in32bit_mult_out_p_0_4;
    wire multiplier_in32bit_mult_out_p_0_3;
    wire multiplier_in32bit_mult_out_p_0_2;
    wire multiplier_in32bit_mult_out_p_0_1;
    wire multiplier_in32bit_mult_out_p_0_0;
    wire multiplier_in32bit_mult_out_signedp_0;
    wire multiplier_in32bit_mult_out_rob_1_17;
    wire multiplier_in32bit_mult_out_roa_1_17;
    wire multiplier_in32bit_mult_out_rob_1_16;
    wire multiplier_in32bit_mult_out_roa_1_16;
    wire multiplier_in32bit_mult_out_rob_1_15;
    wire multiplier_in32bit_mult_out_roa_1_15;
    wire multiplier_in32bit_mult_out_rob_1_14;
    wire multiplier_in32bit_mult_out_roa_1_14;
    wire multiplier_in32bit_mult_out_rob_1_13;
    wire multiplier_in32bit_mult_out_roa_1_13;
    wire multiplier_in32bit_mult_out_rob_1_12;
    wire multiplier_in32bit_mult_out_roa_1_12;
    wire multiplier_in32bit_mult_out_rob_1_11;
    wire multiplier_in32bit_mult_out_roa_1_11;
    wire multiplier_in32bit_mult_out_rob_1_10;
    wire multiplier_in32bit_mult_out_roa_1_10;
    wire multiplier_in32bit_mult_out_rob_1_9;
    wire multiplier_in32bit_mult_out_roa_1_9;
    wire multiplier_in32bit_mult_out_rob_1_8;
    wire multiplier_in32bit_mult_out_roa_1_8;
    wire multiplier_in32bit_mult_out_rob_1_7;
    wire multiplier_in32bit_mult_out_roa_1_7;
    wire multiplier_in32bit_mult_out_rob_1_6;
    wire multiplier_in32bit_mult_out_roa_1_6;
    wire multiplier_in32bit_mult_out_rob_1_5;
    wire multiplier_in32bit_mult_out_roa_1_5;
    wire multiplier_in32bit_mult_out_rob_1_4;
    wire multiplier_in32bit_mult_out_roa_1_4;
    wire multiplier_in32bit_mult_out_rob_1_3;
    wire multiplier_in32bit_mult_out_roa_1_3;
    wire multiplier_in32bit_mult_out_rob_1_2;
    wire multiplier_in32bit_mult_out_roa_1_2;
    wire multiplier_in32bit_mult_out_rob_1_1;
    wire multiplier_in32bit_mult_out_roa_1_1;
    wire multiplier_in32bit_mult_out_rob_1_0;
    wire multiplier_in32bit_mult_out_roa_1_0;
    wire multiplier_in32bit_mult_out_p_1_35;
    wire multiplier_in32bit_mult_out_p_1_34;
    wire multiplier_in32bit_mult_out_p_1_33;
    wire multiplier_in32bit_mult_out_p_1_32;
    wire multiplier_in32bit_mult_out_p_1_31;
    wire multiplier_in32bit_mult_out_p_1_30;
    wire multiplier_in32bit_mult_out_p_1_29;
    wire multiplier_in32bit_mult_out_p_1_28;
    wire multiplier_in32bit_mult_out_p_1_27;
    wire multiplier_in32bit_mult_out_p_1_26;
    wire multiplier_in32bit_mult_out_p_1_25;
    wire multiplier_in32bit_mult_out_p_1_24;
    wire multiplier_in32bit_mult_out_p_1_23;
    wire multiplier_in32bit_mult_out_p_1_22;
    wire multiplier_in32bit_mult_out_p_1_21;
    wire multiplier_in32bit_mult_out_p_1_20;
    wire multiplier_in32bit_mult_out_p_1_19;
    wire multiplier_in32bit_mult_out_p_1_18;
    wire multiplier_in32bit_mult_out_p_1_17;
    wire multiplier_in32bit_mult_out_p_1_16;
    wire multiplier_in32bit_mult_out_p_1_15;
    wire multiplier_in32bit_mult_out_p_1_14;
    wire multiplier_in32bit_mult_out_p_1_13;
    wire multiplier_in32bit_mult_out_p_1_12;
    wire multiplier_in32bit_mult_out_p_1_11;
    wire multiplier_in32bit_mult_out_p_1_10;
    wire multiplier_in32bit_mult_out_p_1_9;
    wire multiplier_in32bit_mult_out_p_1_8;
    wire multiplier_in32bit_mult_out_p_1_7;
    wire multiplier_in32bit_mult_out_p_1_6;
    wire multiplier_in32bit_mult_out_p_1_5;
    wire multiplier_in32bit_mult_out_p_1_4;
    wire multiplier_in32bit_mult_out_p_1_3;
    wire multiplier_in32bit_mult_out_p_1_2;
    wire multiplier_in32bit_mult_out_p_1_1;
    wire multiplier_in32bit_mult_out_p_1_0;
    wire multiplier_in32bit_mult_out_signedp_1;
    wire scuba_vhi;
    wire scuba_vlo;

    defparam dsp_alu_0.CLK3_DIV = "ENABLED" ;
    defparam dsp_alu_0.CLK2_DIV = "ENABLED" ;
    defparam dsp_alu_0.CLK1_DIV = "ENABLED" ;
    defparam dsp_alu_0.CLK0_DIV = "ENABLED" ;
    defparam dsp_alu_0.REG_INPUTCFB_RST = "RST0" ;
    defparam dsp_alu_0.REG_INPUTCFB_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTCFB_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEIN_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEIN_0_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP1_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP1_0_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OPCODEOP0_0_CLK = "NONE" ;
    defparam dsp_alu_0.REG_INPUTC1_RST = "RST0" ;
    defparam dsp_alu_0.REG_INPUTC1_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTC1_CLK = "NONE" ;
    defparam dsp_alu_0.REG_INPUTC0_RST = "RST0" ;
    defparam dsp_alu_0.REG_INPUTC0_CE = "CE0" ;
    defparam dsp_alu_0.REG_INPUTC0_CLK = "NONE" ;
    defparam dsp_alu_0.LEGACY = "DISABLED" ;
    defparam dsp_alu_0.REG_FLAG_RST = "RST0" ;
    defparam dsp_alu_0.REG_FLAG_CE = "CE0" ;
    defparam dsp_alu_0.REG_FLAG_CLK = "NONE" ;
    defparam dsp_alu_0.REG_OUTPUT1_RST = "RST0" ;
    defparam dsp_alu_0.REG_OUTPUT1_CE = "CE0" ;
    defparam dsp_alu_0.REG_OUTPUT1_CLK = "CLK0" ;
    defparam dsp_alu_0.REG_OUTPUT0_RST = "RST0" ;
    defparam dsp_alu_0.REG_OUTPUT0_CE = "CE0" ;
    defparam dsp_alu_0.REG_OUTPUT0_CLK = "CLK0" ;
    defparam dsp_alu_0.MULT9_MODE = "DISABLED" ;
    defparam dsp_alu_0.RNDPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MASKPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MCPAT = "0x00000000000000" ;
    defparam dsp_alu_0.MASK01 = "0x00000000000000" ;
    defparam dsp_alu_0.MASKPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_0.MCPAT_SOURCE = "STATIC" ;
    defparam dsp_alu_0.RESETMODE = "ASYNC" ;
    defparam dsp_alu_0.GSR = "ENABLED" ;
    ALU54B dsp_alu_0 (.A35(multiplier_in32bit_mult_out_rob_0_17), .A34(multiplier_in32bit_mult_out_rob_0_16), 
        .A33(multiplier_in32bit_mult_out_rob_0_15), .A32(multiplier_in32bit_mult_out_rob_0_14), 
        .A31(multiplier_in32bit_mult_out_rob_0_13), .A30(multiplier_in32bit_mult_out_rob_0_12), 
        .A29(multiplier_in32bit_mult_out_rob_0_11), .A28(multiplier_in32bit_mult_out_rob_0_10), 
        .A27(multiplier_in32bit_mult_out_rob_0_9), .A26(multiplier_in32bit_mult_out_rob_0_8), 
        .A25(multiplier_in32bit_mult_out_rob_0_7), .A24(multiplier_in32bit_mult_out_rob_0_6), 
        .A23(multiplier_in32bit_mult_out_rob_0_5), .A22(multiplier_in32bit_mult_out_rob_0_4), 
        .A21(multiplier_in32bit_mult_out_rob_0_3), .A20(multiplier_in32bit_mult_out_rob_0_2), 
        .A19(multiplier_in32bit_mult_out_rob_0_1), .A18(multiplier_in32bit_mult_out_rob_0_0), 
        .A17(multiplier_in32bit_mult_out_roa_0_17), .A16(multiplier_in32bit_mult_out_roa_0_16), 
        .A15(multiplier_in32bit_mult_out_roa_0_15), .A14(multiplier_in32bit_mult_out_roa_0_14), 
        .A13(multiplier_in32bit_mult_out_roa_0_13), .A12(multiplier_in32bit_mult_out_roa_0_12), 
        .A11(multiplier_in32bit_mult_out_roa_0_11), .A10(multiplier_in32bit_mult_out_roa_0_10), 
        .A9(multiplier_in32bit_mult_out_roa_0_9), .A8(multiplier_in32bit_mult_out_roa_0_8), 
        .A7(multiplier_in32bit_mult_out_roa_0_7), .A6(multiplier_in32bit_mult_out_roa_0_6), 
        .A5(multiplier_in32bit_mult_out_roa_0_5), .A4(multiplier_in32bit_mult_out_roa_0_4), 
        .A3(multiplier_in32bit_mult_out_roa_0_3), .A2(multiplier_in32bit_mult_out_roa_0_2), 
        .A1(multiplier_in32bit_mult_out_roa_0_1), .A0(multiplier_in32bit_mult_out_roa_0_0), 
        .B35(multiplier_in32bit_mult_out_rob_1_17), .B34(multiplier_in32bit_mult_out_rob_1_16), 
        .B33(multiplier_in32bit_mult_out_rob_1_15), .B32(multiplier_in32bit_mult_out_rob_1_14), 
        .B31(multiplier_in32bit_mult_out_rob_1_13), .B30(multiplier_in32bit_mult_out_rob_1_12), 
        .B29(multiplier_in32bit_mult_out_rob_1_11), .B28(multiplier_in32bit_mult_out_rob_1_10), 
        .B27(multiplier_in32bit_mult_out_rob_1_9), .B26(multiplier_in32bit_mult_out_rob_1_8), 
        .B25(multiplier_in32bit_mult_out_rob_1_7), .B24(multiplier_in32bit_mult_out_rob_1_6), 
        .B23(multiplier_in32bit_mult_out_rob_1_5), .B22(multiplier_in32bit_mult_out_rob_1_4), 
        .B21(multiplier_in32bit_mult_out_rob_1_3), .B20(multiplier_in32bit_mult_out_rob_1_2), 
        .B19(multiplier_in32bit_mult_out_rob_1_1), .B18(multiplier_in32bit_mult_out_rob_1_0), 
        .B17(multiplier_in32bit_mult_out_roa_1_17), .B16(multiplier_in32bit_mult_out_roa_1_16), 
        .B15(multiplier_in32bit_mult_out_roa_1_15), .B14(multiplier_in32bit_mult_out_roa_1_14), 
        .B13(multiplier_in32bit_mult_out_roa_1_13), .B12(multiplier_in32bit_mult_out_roa_1_12), 
        .B11(multiplier_in32bit_mult_out_roa_1_11), .B10(multiplier_in32bit_mult_out_roa_1_10), 
        .B9(multiplier_in32bit_mult_out_roa_1_9), .B8(multiplier_in32bit_mult_out_roa_1_8), 
        .B7(multiplier_in32bit_mult_out_roa_1_7), .B6(multiplier_in32bit_mult_out_roa_1_6), 
        .B5(multiplier_in32bit_mult_out_roa_1_5), .B4(multiplier_in32bit_mult_out_roa_1_4), 
        .B3(multiplier_in32bit_mult_out_roa_1_3), .B2(multiplier_in32bit_mult_out_roa_1_2), 
        .B1(multiplier_in32bit_mult_out_roa_1_1), .B0(multiplier_in32bit_mult_out_roa_1_0), 
        .CFB53(scuba_vlo), .CFB52(scuba_vlo), .CFB51(scuba_vlo), .CFB50(scuba_vlo), 
        .CFB49(scuba_vlo), .CFB48(scuba_vlo), .CFB47(scuba_vlo), .CFB46(scuba_vlo), 
        .CFB45(scuba_vlo), .CFB44(scuba_vlo), .CFB43(scuba_vlo), .CFB42(scuba_vlo), 
        .CFB41(scuba_vlo), .CFB40(scuba_vlo), .CFB39(scuba_vlo), .CFB38(scuba_vlo), 
        .CFB37(scuba_vlo), .CFB36(scuba_vlo), .CFB35(scuba_vlo), .CFB34(scuba_vlo), 
        .CFB33(scuba_vlo), .CFB32(scuba_vlo), .CFB31(scuba_vlo), .CFB30(scuba_vlo), 
        .CFB29(scuba_vlo), .CFB28(scuba_vlo), .CFB27(scuba_vlo), .CFB26(scuba_vlo), 
        .CFB25(scuba_vlo), .CFB24(scuba_vlo), .CFB23(scuba_vlo), .CFB22(scuba_vlo), 
        .CFB21(scuba_vlo), .CFB20(scuba_vlo), .CFB19(scuba_vlo), .CFB18(scuba_vlo), 
        .CFB17(scuba_vlo), .CFB16(scuba_vlo), .CFB15(scuba_vlo), .CFB14(scuba_vlo), 
        .CFB13(scuba_vlo), .CFB12(scuba_vlo), .CFB11(scuba_vlo), .CFB10(scuba_vlo), 
        .CFB9(scuba_vlo), .CFB8(scuba_vlo), .CFB7(scuba_vlo), .CFB6(scuba_vlo), 
        .CFB5(scuba_vlo), .CFB4(scuba_vlo), .CFB3(scuba_vlo), .CFB2(scuba_vlo), 
        .CFB1(scuba_vlo), .CFB0(scuba_vlo), .C53(scuba_vlo), .C52(scuba_vlo), 
        .C51(scuba_vlo), .C50(scuba_vlo), .C49(scuba_vlo), .C48(scuba_vlo), 
        .C47(scuba_vlo), .C46(scuba_vlo), .C45(scuba_vlo), .C44(scuba_vlo), 
        .C43(scuba_vlo), .C42(scuba_vlo), .C41(scuba_vlo), .C40(scuba_vlo), 
        .C39(scuba_vlo), .C38(scuba_vlo), .C37(scuba_vlo), .C36(scuba_vlo), 
        .C35(scuba_vlo), .C34(scuba_vlo), .C33(scuba_vlo), .C32(scuba_vlo), 
        .C31(scuba_vlo), .C30(scuba_vlo), .C29(scuba_vlo), .C28(scuba_vlo), 
        .C27(scuba_vlo), .C26(scuba_vlo), .C25(scuba_vlo), .C24(scuba_vlo), 
        .C23(scuba_vlo), .C22(scuba_vlo), .C21(scuba_vlo), .C20(scuba_vlo), 
        .C19(scuba_vlo), .C18(scuba_vlo), .C17(scuba_vlo), .C16(scuba_vlo), 
        .C15(scuba_vlo), .C14(scuba_vlo), .C13(scuba_vlo), .C12(scuba_vlo), 
        .C11(scuba_vlo), .C10(scuba_vlo), .C9(scuba_vlo), .C8(scuba_vlo), 
        .C7(scuba_vlo), .C6(scuba_vlo), .C5(scuba_vlo), .C4(scuba_vlo), 
        .C3(scuba_vlo), .C2(scuba_vlo), .C1(scuba_vlo), .C0(scuba_vlo), 
        .CE0(ClkEn), .CE1(scuba_vhi), .CE2(scuba_vhi), .CE3(scuba_vhi), 
        .CLK0(Clock), .CLK1(scuba_vlo), .CLK2(scuba_vlo), .CLK3(scuba_vlo), 
        .RST0(Aclr), .RST1(scuba_vlo), .RST2(scuba_vlo), .RST3(scuba_vlo), 
        .SIGNEDIA(multiplier_in32bit_mult_out_signedp_0), .SIGNEDIB(multiplier_in32bit_mult_out_signedp_1), 
        .SIGNEDCIN(multiplier_in32bit_alu_signedcin_1_0), .MA35(multiplier_in32bit_mult_out_p_0_35), 
        .MA34(multiplier_in32bit_mult_out_p_0_34), .MA33(multiplier_in32bit_mult_out_p_0_33), 
        .MA32(multiplier_in32bit_mult_out_p_0_32), .MA31(multiplier_in32bit_mult_out_p_0_31), 
        .MA30(multiplier_in32bit_mult_out_p_0_30), .MA29(multiplier_in32bit_mult_out_p_0_29), 
        .MA28(multiplier_in32bit_mult_out_p_0_28), .MA27(multiplier_in32bit_mult_out_p_0_27), 
        .MA26(multiplier_in32bit_mult_out_p_0_26), .MA25(multiplier_in32bit_mult_out_p_0_25), 
        .MA24(multiplier_in32bit_mult_out_p_0_24), .MA23(multiplier_in32bit_mult_out_p_0_23), 
        .MA22(multiplier_in32bit_mult_out_p_0_22), .MA21(multiplier_in32bit_mult_out_p_0_21), 
        .MA20(multiplier_in32bit_mult_out_p_0_20), .MA19(multiplier_in32bit_mult_out_p_0_19), 
        .MA18(multiplier_in32bit_mult_out_p_0_18), .MA17(multiplier_in32bit_mult_out_p_0_17), 
        .MA16(multiplier_in32bit_mult_out_p_0_16), .MA15(multiplier_in32bit_mult_out_p_0_15), 
        .MA14(multiplier_in32bit_mult_out_p_0_14), .MA13(multiplier_in32bit_mult_out_p_0_13), 
        .MA12(multiplier_in32bit_mult_out_p_0_12), .MA11(multiplier_in32bit_mult_out_p_0_11), 
        .MA10(multiplier_in32bit_mult_out_p_0_10), .MA9(multiplier_in32bit_mult_out_p_0_9), 
        .MA8(multiplier_in32bit_mult_out_p_0_8), .MA7(multiplier_in32bit_mult_out_p_0_7), 
        .MA6(multiplier_in32bit_mult_out_p_0_6), .MA5(multiplier_in32bit_mult_out_p_0_5), 
        .MA4(multiplier_in32bit_mult_out_p_0_4), .MA3(multiplier_in32bit_mult_out_p_0_3), 
        .MA2(multiplier_in32bit_mult_out_p_0_2), .MA1(multiplier_in32bit_mult_out_p_0_1), 
        .MA0(multiplier_in32bit_mult_out_p_0_0), .MB35(multiplier_in32bit_mult_out_p_1_35), 
        .MB34(multiplier_in32bit_mult_out_p_1_34), .MB33(multiplier_in32bit_mult_out_p_1_33), 
        .MB32(multiplier_in32bit_mult_out_p_1_32), .MB31(multiplier_in32bit_mult_out_p_1_31), 
        .MB30(multiplier_in32bit_mult_out_p_1_30), .MB29(multiplier_in32bit_mult_out_p_1_29), 
        .MB28(multiplier_in32bit_mult_out_p_1_28), .MB27(multiplier_in32bit_mult_out_p_1_27), 
        .MB26(multiplier_in32bit_mult_out_p_1_26), .MB25(multiplier_in32bit_mult_out_p_1_25), 
        .MB24(multiplier_in32bit_mult_out_p_1_24), .MB23(multiplier_in32bit_mult_out_p_1_23), 
        .MB22(multiplier_in32bit_mult_out_p_1_22), .MB21(multiplier_in32bit_mult_out_p_1_21), 
        .MB20(multiplier_in32bit_mult_out_p_1_20), .MB19(multiplier_in32bit_mult_out_p_1_19), 
        .MB18(multiplier_in32bit_mult_out_p_1_18), .MB17(multiplier_in32bit_mult_out_p_1_17), 
        .MB16(multiplier_in32bit_mult_out_p_1_16), .MB15(multiplier_in32bit_mult_out_p_1_15), 
        .MB14(multiplier_in32bit_mult_out_p_1_14), .MB13(multiplier_in32bit_mult_out_p_1_13), 
        .MB12(multiplier_in32bit_mult_out_p_1_12), .MB11(multiplier_in32bit_mult_out_p_1_11), 
        .MB10(multiplier_in32bit_mult_out_p_1_10), .MB9(multiplier_in32bit_mult_out_p_1_9), 
        .MB8(multiplier_in32bit_mult_out_p_1_8), .MB7(multiplier_in32bit_mult_out_p_1_7), 
        .MB6(multiplier_in32bit_mult_out_p_1_6), .MB5(multiplier_in32bit_mult_out_p_1_5), 
        .MB4(multiplier_in32bit_mult_out_p_1_4), .MB3(multiplier_in32bit_mult_out_p_1_3), 
        .MB2(multiplier_in32bit_mult_out_p_1_2), .MB1(multiplier_in32bit_mult_out_p_1_1), 
        .MB0(multiplier_in32bit_mult_out_p_1_0), .CIN53(multiplier_in32bit_alu_in_cin_1_0_53), 
        .CIN52(multiplier_in32bit_alu_in_cin_1_0_52), .CIN51(multiplier_in32bit_alu_in_cin_1_0_51), 
        .CIN50(multiplier_in32bit_alu_in_cin_1_0_50), .CIN49(multiplier_in32bit_alu_in_cin_1_0_49), 
        .CIN48(multiplier_in32bit_alu_in_cin_1_0_48), .CIN47(multiplier_in32bit_alu_in_cin_1_0_47), 
        .CIN46(multiplier_in32bit_alu_in_cin_1_0_46), .CIN45(multiplier_in32bit_alu_in_cin_1_0_45), 
        .CIN44(multiplier_in32bit_alu_in_cin_1_0_44), .CIN43(multiplier_in32bit_alu_in_cin_1_0_43), 
        .CIN42(multiplier_in32bit_alu_in_cin_1_0_42), .CIN41(multiplier_in32bit_alu_in_cin_1_0_41), 
        .CIN40(multiplier_in32bit_alu_in_cin_1_0_40), .CIN39(multiplier_in32bit_alu_in_cin_1_0_39), 
        .CIN38(multiplier_in32bit_alu_in_cin_1_0_38), .CIN37(multiplier_in32bit_alu_in_cin_1_0_37), 
        .CIN36(multiplier_in32bit_alu_in_cin_1_0_36), .CIN35(multiplier_in32bit_alu_in_cin_1_0_35), 
        .CIN34(multiplier_in32bit_alu_in_cin_1_0_34), .CIN33(multiplier_in32bit_alu_in_cin_1_0_33), 
        .CIN32(multiplier_in32bit_alu_in_cin_1_0_32), .CIN31(multiplier_in32bit_alu_in_cin_1_0_31), 
        .CIN30(multiplier_in32bit_alu_in_cin_1_0_30), .CIN29(multiplier_in32bit_alu_in_cin_1_0_29), 
        .CIN28(multiplier_in32bit_alu_in_cin_1_0_28), .CIN27(multiplier_in32bit_alu_in_cin_1_0_27), 
        .CIN26(multiplier_in32bit_alu_in_cin_1_0_26), .CIN25(multiplier_in32bit_alu_in_cin_1_0_25), 
        .CIN24(multiplier_in32bit_alu_in_cin_1_0_24), .CIN23(multiplier_in32bit_alu_in_cin_1_0_23), 
        .CIN22(multiplier_in32bit_alu_in_cin_1_0_22), .CIN21(multiplier_in32bit_alu_in_cin_1_0_21), 
        .CIN20(multiplier_in32bit_alu_in_cin_1_0_20), .CIN19(multiplier_in32bit_alu_in_cin_1_0_19), 
        .CIN18(multiplier_in32bit_alu_in_cin_1_0_18), .CIN17(multiplier_in32bit_alu_in_cin_1_0_17), 
        .CIN16(multiplier_in32bit_alu_in_cin_1_0_16), .CIN15(multiplier_in32bit_alu_in_cin_1_0_15), 
        .CIN14(multiplier_in32bit_alu_in_cin_1_0_14), .CIN13(multiplier_in32bit_alu_in_cin_1_0_13), 
        .CIN12(multiplier_in32bit_alu_in_cin_1_0_12), .CIN11(multiplier_in32bit_alu_in_cin_1_0_11), 
        .CIN10(multiplier_in32bit_alu_in_cin_1_0_10), .CIN9(multiplier_in32bit_alu_in_cin_1_0_9), 
        .CIN8(multiplier_in32bit_alu_in_cin_1_0_8), .CIN7(multiplier_in32bit_alu_in_cin_1_0_7), 
        .CIN6(multiplier_in32bit_alu_in_cin_1_0_6), .CIN5(multiplier_in32bit_alu_in_cin_1_0_5), 
        .CIN4(multiplier_in32bit_alu_in_cin_1_0_4), .CIN3(multiplier_in32bit_alu_in_cin_1_0_3), 
        .CIN2(multiplier_in32bit_alu_in_cin_1_0_2), .CIN1(multiplier_in32bit_alu_in_cin_1_0_1), 
        .CIN0(multiplier_in32bit_alu_in_cin_1_0_0), .OP10(scuba_vlo), .OP9(scuba_vhi), 
        .OP8(scuba_vlo), .OP7(scuba_vlo), .OP6(scuba_vlo), .OP5(scuba_vlo), 
        .OP4(scuba_vlo), .OP3(scuba_vlo), .OP2(scuba_vlo), .OP1(scuba_vlo), 
        .OP0(scuba_vhi), .R53(multiplier_in32bit_alu_output_r_1_0_53), .R52(multiplier_in32bit_alu_output_r_1_0_52), 
        .R51(multiplier_in32bit_alu_output_r_1_0_51), .R50(multiplier_in32bit_alu_output_r_1_0_50), 
        .R49(multiplier_in32bit_alu_output_r_1_0_49), .R48(multiplier_in32bit_alu_output_r_1_0_48), 
        .R47(multiplier_in32bit_alu_output_r_1_0_47), .R46(multiplier_in32bit_alu_output_r_1_0_46), 
        .R45(multiplier_in32bit_alu_output_r_1_0_45), .R44(multiplier_in32bit_alu_output_r_1_0_44), 
        .R43(multiplier_in32bit_alu_output_r_1_0_43), .R42(multiplier_in32bit_alu_output_r_1_0_42), 
        .R41(multiplier_in32bit_alu_output_r_1_0_41), .R40(multiplier_in32bit_alu_output_r_1_0_40), 
        .R39(multiplier_in32bit_alu_output_r_1_0_39), .R38(multiplier_in32bit_alu_output_r_1_0_38), 
        .R37(multiplier_in32bit_alu_output_r_1_0_37), .R36(multiplier_in32bit_alu_output_r_1_0_36), 
        .R35(multiplier_in32bit_alu_output_r_1_0_35), .R34(multiplier_in32bit_alu_output_r_1_0_34), 
        .R33(multiplier_in32bit_alu_output_r_1_0_33), .R32(multiplier_in32bit_alu_output_r_1_0_32), 
        .R31(multiplier_in32bit_alu_output_r_1_0_31), .R30(multiplier_in32bit_alu_output_r_1_0_30), 
        .R29(multiplier_in32bit_alu_output_r_1_0_29), .R28(multiplier_in32bit_alu_output_r_1_0_28), 
        .R27(multiplier_in32bit_alu_output_r_1_0_27), .R26(multiplier_in32bit_alu_output_r_1_0_26), 
        .R25(multiplier_in32bit_alu_output_r_1_0_25), .R24(multiplier_in32bit_alu_output_r_1_0_24), 
        .R23(multiplier_in32bit_alu_output_r_1_0_23), .R22(multiplier_in32bit_alu_output_r_1_0_22), 
        .R21(multiplier_in32bit_alu_output_r_1_0_21), .R20(multiplier_in32bit_alu_output_r_1_0_20), 
        .R19(multiplier_in32bit_alu_output_r_1_0_19), .R18(multiplier_in32bit_alu_output_r_1_0_18), 
        .R17(multiplier_in32bit_alu_output_r_1_0_17), .R16(multiplier_in32bit_alu_output_r_1_0_16), 
        .R15(multiplier_in32bit_alu_output_r_1_0_15), .R14(multiplier_in32bit_alu_output_r_1_0_14), 
        .R13(multiplier_in32bit_alu_output_r_1_0_13), .R12(multiplier_in32bit_alu_output_r_1_0_12), 
        .R11(multiplier_in32bit_alu_output_r_1_0_11), .R10(multiplier_in32bit_alu_output_r_1_0_10), 
        .R9(multiplier_in32bit_alu_output_r_1_0_9), .R8(multiplier_in32bit_alu_output_r_1_0_8), 
        .R7(multiplier_in32bit_alu_output_r_1_0_7), .R6(multiplier_in32bit_alu_output_r_1_0_6), 
        .R5(multiplier_in32bit_alu_output_r_1_0_5), .R4(multiplier_in32bit_alu_output_r_1_0_4), 
        .R3(multiplier_in32bit_alu_output_r_1_0_3), .R2(multiplier_in32bit_alu_output_r_1_0_2), 
        .R1(multiplier_in32bit_alu_output_r_1_0_1), .R0(multiplier_in32bit_alu_output_r_1_0_0), 
        .CO53(), .CO52(), .CO51(), .CO50(), .CO49(), .CO48(), .CO47(), .CO46(), 
        .CO45(), .CO44(), .CO43(), .CO42(), .CO41(), .CO40(), .CO39(), .CO38(), 
        .CO37(), .CO36(), .CO35(), .CO34(), .CO33(), .CO32(), .CO31(), .CO30(), 
        .CO29(), .CO28(), .CO27(), .CO26(), .CO25(), .CO24(), .CO23(), .CO22(), 
        .CO21(), .CO20(), .CO19(), .CO18(), .CO17(), .CO16(), .CO15(), .CO14(), 
        .CO13(), .CO12(), .CO11(), .CO10(), .CO9(), .CO8(), .CO7(), .CO6(), 
        .CO5(), .CO4(), .CO3(), .CO2(), .CO1(), .CO0(), .EQZ(), .EQZM(), 
        .EQOM(), .EQPAT(), .EQPATB(), .OVER(), .UNDER(), .OVERUNDER(), .SIGNEDR(multiplier_in32bit_alu_signedr_1_0));

    defparam dsp_mult_1.CLK3_DIV = "ENABLED" ;
    defparam dsp_mult_1.CLK2_DIV = "ENABLED" ;
    defparam dsp_mult_1.CLK1_DIV = "ENABLED" ;
    defparam dsp_mult_1.CLK0_DIV = "ENABLED" ;
    defparam dsp_mult_1.HIGHSPEED_CLK = "NONE" ;
    defparam dsp_mult_1.REG_INPUTC_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTC_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTC_CLK = "NONE" ;
    defparam dsp_mult_1.SOURCEB_MODE = "B_SHIFT" ;
    defparam dsp_mult_1.MULT_BYPASS = "DISABLED" ;
    defparam dsp_mult_1.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_1.RESETMODE = "ASYNC" ;
    defparam dsp_mult_1.GSR = "ENABLED" ;
    defparam dsp_mult_1.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_mult_1.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_mult_1.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_1.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_1.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_mult_1.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_1.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTB_CLK = "NONE" ;
    defparam dsp_mult_1.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_1.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_1.REG_INPUTA_CLK = "NONE" ;
    MULT18X18D dsp_mult_1 (.A17(DataA[9]), .A16(DataA[8]), .A15(DataA[7]), 
        .A14(DataA[6]), .A13(DataA[5]), .A12(DataA[4]), .A11(DataA[3]), 
        .A10(DataA[2]), .A9(DataA[1]), .A8(DataA[0]), .A7(scuba_vlo), .A6(scuba_vlo), 
        .A5(scuba_vlo), .A4(scuba_vlo), .A3(scuba_vlo), .A2(scuba_vlo), 
        .A1(scuba_vlo), .A0(scuba_vlo), .B17(DataB[13]), .B16(DataB[12]), 
        .B15(DataB[11]), .B14(DataB[10]), .B13(DataB[9]), .B12(DataB[8]), 
        .B11(DataB[7]), .B10(DataB[6]), .B9(DataB[5]), .B8(DataB[4]), .B7(DataB[3]), 
        .B6(DataB[2]), .B5(DataB[1]), .B4(DataB[0]), .B3(scuba_vlo), .B2(scuba_vlo), 
        .B1(scuba_vlo), .B0(scuba_vlo), .C17(scuba_vlo), .C16(scuba_vlo), 
        .C15(scuba_vlo), .C14(scuba_vlo), .C13(scuba_vlo), .C12(scuba_vlo), 
        .C11(scuba_vlo), .C10(scuba_vlo), .C9(scuba_vlo), .C8(scuba_vlo), 
        .C7(scuba_vlo), .C6(scuba_vlo), .C5(scuba_vlo), .C4(scuba_vlo), 
        .C3(scuba_vlo), .C2(scuba_vlo), .C1(scuba_vlo), .C0(scuba_vlo), 
        .SIGNEDA(scuba_vlo), .SIGNEDB(scuba_vlo), .SOURCEA(scuba_vlo), .SOURCEB(scuba_vlo), 
        .CE0(ClkEn), .CE1(scuba_vhi), .CE2(scuba_vhi), .CE3(scuba_vhi), 
        .CLK0(Clock), .CLK1(scuba_vlo), .CLK2(scuba_vlo), .CLK3(scuba_vlo), 
        .RST0(Aclr), .RST1(scuba_vlo), .RST2(scuba_vlo), .RST3(scuba_vlo), 
        .SRIA17(scuba_vlo), .SRIA16(scuba_vlo), .SRIA15(scuba_vlo), .SRIA14(scuba_vlo), 
        .SRIA13(scuba_vlo), .SRIA12(scuba_vlo), .SRIA11(scuba_vlo), .SRIA10(scuba_vlo), 
        .SRIA9(scuba_vlo), .SRIA8(scuba_vlo), .SRIA7(scuba_vlo), .SRIA6(scuba_vlo), 
        .SRIA5(scuba_vlo), .SRIA4(scuba_vlo), .SRIA3(scuba_vlo), .SRIA2(scuba_vlo), 
        .SRIA1(scuba_vlo), .SRIA0(scuba_vlo), .SRIB17(scuba_vlo), .SRIB16(scuba_vlo), 
        .SRIB15(scuba_vlo), .SRIB14(scuba_vlo), .SRIB13(scuba_vlo), .SRIB12(scuba_vlo), 
        .SRIB11(scuba_vlo), .SRIB10(scuba_vlo), .SRIB9(scuba_vlo), .SRIB8(scuba_vlo), 
        .SRIB7(scuba_vlo), .SRIB6(scuba_vlo), .SRIB5(scuba_vlo), .SRIB4(scuba_vlo), 
        .SRIB3(scuba_vlo), .SRIB2(scuba_vlo), .SRIB1(scuba_vlo), .SRIB0(scuba_vlo), 
        .SROA17(), .SROA16(), .SROA15(), .SROA14(), .SROA13(), .SROA12(), 
        .SROA11(), .SROA10(), .SROA9(), .SROA8(), .SROA7(), .SROA6(), .SROA5(), 
        .SROA4(), .SROA3(), .SROA2(), .SROA1(), .SROA0(), .SROB17(), .SROB16(), 
        .SROB15(), .SROB14(), .SROB13(), .SROB12(), .SROB11(), .SROB10(), 
        .SROB9(), .SROB8(), .SROB7(), .SROB6(), .SROB5(), .SROB4(), .SROB3(), 
        .SROB2(), .SROB1(), .SROB0(), .ROA17(multiplier_in32bit_mult_out_roa_0_17), 
        .ROA16(multiplier_in32bit_mult_out_roa_0_16), .ROA15(multiplier_in32bit_mult_out_roa_0_15), 
        .ROA14(multiplier_in32bit_mult_out_roa_0_14), .ROA13(multiplier_in32bit_mult_out_roa_0_13), 
        .ROA12(multiplier_in32bit_mult_out_roa_0_12), .ROA11(multiplier_in32bit_mult_out_roa_0_11), 
        .ROA10(multiplier_in32bit_mult_out_roa_0_10), .ROA9(multiplier_in32bit_mult_out_roa_0_9), 
        .ROA8(multiplier_in32bit_mult_out_roa_0_8), .ROA7(multiplier_in32bit_mult_out_roa_0_7), 
        .ROA6(multiplier_in32bit_mult_out_roa_0_6), .ROA5(multiplier_in32bit_mult_out_roa_0_5), 
        .ROA4(multiplier_in32bit_mult_out_roa_0_4), .ROA3(multiplier_in32bit_mult_out_roa_0_3), 
        .ROA2(multiplier_in32bit_mult_out_roa_0_2), .ROA1(multiplier_in32bit_mult_out_roa_0_1), 
        .ROA0(multiplier_in32bit_mult_out_roa_0_0), .ROB17(multiplier_in32bit_mult_out_rob_0_17), 
        .ROB16(multiplier_in32bit_mult_out_rob_0_16), .ROB15(multiplier_in32bit_mult_out_rob_0_15), 
        .ROB14(multiplier_in32bit_mult_out_rob_0_14), .ROB13(multiplier_in32bit_mult_out_rob_0_13), 
        .ROB12(multiplier_in32bit_mult_out_rob_0_12), .ROB11(multiplier_in32bit_mult_out_rob_0_11), 
        .ROB10(multiplier_in32bit_mult_out_rob_0_10), .ROB9(multiplier_in32bit_mult_out_rob_0_9), 
        .ROB8(multiplier_in32bit_mult_out_rob_0_8), .ROB7(multiplier_in32bit_mult_out_rob_0_7), 
        .ROB6(multiplier_in32bit_mult_out_rob_0_6), .ROB5(multiplier_in32bit_mult_out_rob_0_5), 
        .ROB4(multiplier_in32bit_mult_out_rob_0_4), .ROB3(multiplier_in32bit_mult_out_rob_0_3), 
        .ROB2(multiplier_in32bit_mult_out_rob_0_2), .ROB1(multiplier_in32bit_mult_out_rob_0_1), 
        .ROB0(multiplier_in32bit_mult_out_rob_0_0), .ROC17(), .ROC16(), 
        .ROC15(), .ROC14(), .ROC13(), .ROC12(), .ROC11(), .ROC10(), .ROC9(), 
        .ROC8(), .ROC7(), .ROC6(), .ROC5(), .ROC4(), .ROC3(), .ROC2(), .ROC1(), 
        .ROC0(), .P35(multiplier_in32bit_mult_out_p_0_35), .P34(multiplier_in32bit_mult_out_p_0_34), 
        .P33(multiplier_in32bit_mult_out_p_0_33), .P32(multiplier_in32bit_mult_out_p_0_32), 
        .P31(multiplier_in32bit_mult_out_p_0_31), .P30(multiplier_in32bit_mult_out_p_0_30), 
        .P29(multiplier_in32bit_mult_out_p_0_29), .P28(multiplier_in32bit_mult_out_p_0_28), 
        .P27(multiplier_in32bit_mult_out_p_0_27), .P26(multiplier_in32bit_mult_out_p_0_26), 
        .P25(multiplier_in32bit_mult_out_p_0_25), .P24(multiplier_in32bit_mult_out_p_0_24), 
        .P23(multiplier_in32bit_mult_out_p_0_23), .P22(multiplier_in32bit_mult_out_p_0_22), 
        .P21(multiplier_in32bit_mult_out_p_0_21), .P20(multiplier_in32bit_mult_out_p_0_20), 
        .P19(multiplier_in32bit_mult_out_p_0_19), .P18(multiplier_in32bit_mult_out_p_0_18), 
        .P17(multiplier_in32bit_mult_out_p_0_17), .P16(multiplier_in32bit_mult_out_p_0_16), 
        .P15(multiplier_in32bit_mult_out_p_0_15), .P14(multiplier_in32bit_mult_out_p_0_14), 
        .P13(multiplier_in32bit_mult_out_p_0_13), .P12(multiplier_in32bit_mult_out_p_0_12), 
        .P11(multiplier_in32bit_mult_out_p_0_11), .P10(multiplier_in32bit_mult_out_p_0_10), 
        .P9(multiplier_in32bit_mult_out_p_0_9), .P8(multiplier_in32bit_mult_out_p_0_8), 
        .P7(multiplier_in32bit_mult_out_p_0_7), .P6(multiplier_in32bit_mult_out_p_0_6), 
        .P5(multiplier_in32bit_mult_out_p_0_5), .P4(multiplier_in32bit_mult_out_p_0_4), 
        .P3(multiplier_in32bit_mult_out_p_0_3), .P2(multiplier_in32bit_mult_out_p_0_2), 
        .P1(multiplier_in32bit_mult_out_p_0_1), .P0(multiplier_in32bit_mult_out_p_0_0), 
        .SIGNEDP(multiplier_in32bit_mult_out_signedp_0));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam dsp_mult_0.CLK3_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK2_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK1_DIV = "ENABLED" ;
    defparam dsp_mult_0.CLK0_DIV = "ENABLED" ;
    defparam dsp_mult_0.HIGHSPEED_CLK = "NONE" ;
    defparam dsp_mult_0.REG_INPUTC_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTC_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTC_CLK = "NONE" ;
    defparam dsp_mult_0.SOURCEB_MODE = "B_SHIFT" ;
    defparam dsp_mult_0.MULT_BYPASS = "DISABLED" ;
    defparam dsp_mult_0.CAS_MATCH_REG = "FALSE" ;
    defparam dsp_mult_0.RESETMODE = "ASYNC" ;
    defparam dsp_mult_0.GSR = "ENABLED" ;
    defparam dsp_mult_0.REG_OUTPUT_RST = "RST0" ;
    defparam dsp_mult_0.REG_OUTPUT_CE = "CE0" ;
    defparam dsp_mult_0.REG_OUTPUT_CLK = "NONE" ;
    defparam dsp_mult_0.REG_PIPELINE_RST = "RST0" ;
    defparam dsp_mult_0.REG_PIPELINE_CE = "CE0" ;
    defparam dsp_mult_0.REG_PIPELINE_CLK = "CLK0" ;
    defparam dsp_mult_0.REG_INPUTB_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTB_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTB_CLK = "NONE" ;
    defparam dsp_mult_0.REG_INPUTA_RST = "RST0" ;
    defparam dsp_mult_0.REG_INPUTA_CE = "CE0" ;
    defparam dsp_mult_0.REG_INPUTA_CLK = "NONE" ;
    MULT18X18D dsp_mult_0 (.A17(DataA[9]), .A16(DataA[8]), .A15(DataA[7]), 
        .A14(DataA[6]), .A13(DataA[5]), .A12(DataA[4]), .A11(DataA[3]), 
        .A10(DataA[2]), .A9(DataA[1]), .A8(DataA[0]), .A7(scuba_vlo), .A6(scuba_vlo), 
        .A5(scuba_vlo), .A4(scuba_vlo), .A3(scuba_vlo), .A2(scuba_vlo), 
        .A1(scuba_vlo), .A0(scuba_vlo), .B17(DataB[31]), .B16(DataB[30]), 
        .B15(DataB[29]), .B14(DataB[28]), .B13(DataB[27]), .B12(DataB[26]), 
        .B11(DataB[25]), .B10(DataB[24]), .B9(DataB[23]), .B8(DataB[22]), 
        .B7(DataB[21]), .B6(DataB[20]), .B5(DataB[19]), .B4(DataB[18]), 
        .B3(DataB[17]), .B2(DataB[16]), .B1(DataB[15]), .B0(DataB[14]), 
        .C17(scuba_vlo), .C16(scuba_vlo), .C15(scuba_vlo), .C14(scuba_vlo), 
        .C13(scuba_vlo), .C12(scuba_vlo), .C11(scuba_vlo), .C10(scuba_vlo), 
        .C9(scuba_vlo), .C8(scuba_vlo), .C7(scuba_vlo), .C6(scuba_vlo), 
        .C5(scuba_vlo), .C4(scuba_vlo), .C3(scuba_vlo), .C2(scuba_vlo), 
        .C1(scuba_vlo), .C0(scuba_vlo), .SIGNEDA(scuba_vlo), .SIGNEDB(scuba_vlo), 
        .SOURCEA(scuba_vlo), .SOURCEB(scuba_vlo), .CE0(ClkEn), .CE1(scuba_vhi), 
        .CE2(scuba_vhi), .CE3(scuba_vhi), .CLK0(Clock), .CLK1(scuba_vlo), 
        .CLK2(scuba_vlo), .CLK3(scuba_vlo), .RST0(Aclr), .RST1(scuba_vlo), 
        .RST2(scuba_vlo), .RST3(scuba_vlo), .SRIA17(scuba_vlo), .SRIA16(scuba_vlo), 
        .SRIA15(scuba_vlo), .SRIA14(scuba_vlo), .SRIA13(scuba_vlo), .SRIA12(scuba_vlo), 
        .SRIA11(scuba_vlo), .SRIA10(scuba_vlo), .SRIA9(scuba_vlo), .SRIA8(scuba_vlo), 
        .SRIA7(scuba_vlo), .SRIA6(scuba_vlo), .SRIA5(scuba_vlo), .SRIA4(scuba_vlo), 
        .SRIA3(scuba_vlo), .SRIA2(scuba_vlo), .SRIA1(scuba_vlo), .SRIA0(scuba_vlo), 
        .SRIB17(scuba_vlo), .SRIB16(scuba_vlo), .SRIB15(scuba_vlo), .SRIB14(scuba_vlo), 
        .SRIB13(scuba_vlo), .SRIB12(scuba_vlo), .SRIB11(scuba_vlo), .SRIB10(scuba_vlo), 
        .SRIB9(scuba_vlo), .SRIB8(scuba_vlo), .SRIB7(scuba_vlo), .SRIB6(scuba_vlo), 
        .SRIB5(scuba_vlo), .SRIB4(scuba_vlo), .SRIB3(scuba_vlo), .SRIB2(scuba_vlo), 
        .SRIB1(scuba_vlo), .SRIB0(scuba_vlo), .SROA17(), .SROA16(), .SROA15(), 
        .SROA14(), .SROA13(), .SROA12(), .SROA11(), .SROA10(), .SROA9(), 
        .SROA8(), .SROA7(), .SROA6(), .SROA5(), .SROA4(), .SROA3(), .SROA2(), 
        .SROA1(), .SROA0(), .SROB17(), .SROB16(), .SROB15(), .SROB14(), 
        .SROB13(), .SROB12(), .SROB11(), .SROB10(), .SROB9(), .SROB8(), 
        .SROB7(), .SROB6(), .SROB5(), .SROB4(), .SROB3(), .SROB2(), .SROB1(), 
        .SROB0(), .ROA17(multiplier_in32bit_mult_out_roa_1_17), .ROA16(multiplier_in32bit_mult_out_roa_1_16), 
        .ROA15(multiplier_in32bit_mult_out_roa_1_15), .ROA14(multiplier_in32bit_mult_out_roa_1_14), 
        .ROA13(multiplier_in32bit_mult_out_roa_1_13), .ROA12(multiplier_in32bit_mult_out_roa_1_12), 
        .ROA11(multiplier_in32bit_mult_out_roa_1_11), .ROA10(multiplier_in32bit_mult_out_roa_1_10), 
        .ROA9(multiplier_in32bit_mult_out_roa_1_9), .ROA8(multiplier_in32bit_mult_out_roa_1_8), 
        .ROA7(multiplier_in32bit_mult_out_roa_1_7), .ROA6(multiplier_in32bit_mult_out_roa_1_6), 
        .ROA5(multiplier_in32bit_mult_out_roa_1_5), .ROA4(multiplier_in32bit_mult_out_roa_1_4), 
        .ROA3(multiplier_in32bit_mult_out_roa_1_3), .ROA2(multiplier_in32bit_mult_out_roa_1_2), 
        .ROA1(multiplier_in32bit_mult_out_roa_1_1), .ROA0(multiplier_in32bit_mult_out_roa_1_0), 
        .ROB17(multiplier_in32bit_mult_out_rob_1_17), .ROB16(multiplier_in32bit_mult_out_rob_1_16), 
        .ROB15(multiplier_in32bit_mult_out_rob_1_15), .ROB14(multiplier_in32bit_mult_out_rob_1_14), 
        .ROB13(multiplier_in32bit_mult_out_rob_1_13), .ROB12(multiplier_in32bit_mult_out_rob_1_12), 
        .ROB11(multiplier_in32bit_mult_out_rob_1_11), .ROB10(multiplier_in32bit_mult_out_rob_1_10), 
        .ROB9(multiplier_in32bit_mult_out_rob_1_9), .ROB8(multiplier_in32bit_mult_out_rob_1_8), 
        .ROB7(multiplier_in32bit_mult_out_rob_1_7), .ROB6(multiplier_in32bit_mult_out_rob_1_6), 
        .ROB5(multiplier_in32bit_mult_out_rob_1_5), .ROB4(multiplier_in32bit_mult_out_rob_1_4), 
        .ROB3(multiplier_in32bit_mult_out_rob_1_3), .ROB2(multiplier_in32bit_mult_out_rob_1_2), 
        .ROB1(multiplier_in32bit_mult_out_rob_1_1), .ROB0(multiplier_in32bit_mult_out_rob_1_0), 
        .ROC17(), .ROC16(), .ROC15(), .ROC14(), .ROC13(), .ROC12(), .ROC11(), 
        .ROC10(), .ROC9(), .ROC8(), .ROC7(), .ROC6(), .ROC5(), .ROC4(), 
        .ROC3(), .ROC2(), .ROC1(), .ROC0(), .P35(multiplier_in32bit_mult_out_p_1_35), 
        .P34(multiplier_in32bit_mult_out_p_1_34), .P33(multiplier_in32bit_mult_out_p_1_33), 
        .P32(multiplier_in32bit_mult_out_p_1_32), .P31(multiplier_in32bit_mult_out_p_1_31), 
        .P30(multiplier_in32bit_mult_out_p_1_30), .P29(multiplier_in32bit_mult_out_p_1_29), 
        .P28(multiplier_in32bit_mult_out_p_1_28), .P27(multiplier_in32bit_mult_out_p_1_27), 
        .P26(multiplier_in32bit_mult_out_p_1_26), .P25(multiplier_in32bit_mult_out_p_1_25), 
        .P24(multiplier_in32bit_mult_out_p_1_24), .P23(multiplier_in32bit_mult_out_p_1_23), 
        .P22(multiplier_in32bit_mult_out_p_1_22), .P21(multiplier_in32bit_mult_out_p_1_21), 
        .P20(multiplier_in32bit_mult_out_p_1_20), .P19(multiplier_in32bit_mult_out_p_1_19), 
        .P18(multiplier_in32bit_mult_out_p_1_18), .P17(multiplier_in32bit_mult_out_p_1_17), 
        .P16(multiplier_in32bit_mult_out_p_1_16), .P15(multiplier_in32bit_mult_out_p_1_15), 
        .P14(multiplier_in32bit_mult_out_p_1_14), .P13(multiplier_in32bit_mult_out_p_1_13), 
        .P12(multiplier_in32bit_mult_out_p_1_12), .P11(multiplier_in32bit_mult_out_p_1_11), 
        .P10(multiplier_in32bit_mult_out_p_1_10), .P9(multiplier_in32bit_mult_out_p_1_9), 
        .P8(multiplier_in32bit_mult_out_p_1_8), .P7(multiplier_in32bit_mult_out_p_1_7), 
        .P6(multiplier_in32bit_mult_out_p_1_6), .P5(multiplier_in32bit_mult_out_p_1_5), 
        .P4(multiplier_in32bit_mult_out_p_1_4), .P3(multiplier_in32bit_mult_out_p_1_3), 
        .P2(multiplier_in32bit_mult_out_p_1_2), .P1(multiplier_in32bit_mult_out_p_1_1), 
        .P0(multiplier_in32bit_mult_out_p_1_0), .SIGNEDP(multiplier_in32bit_mult_out_signedp_1));

    assign Result[41] = multiplier_in32bit_alu_output_r_1_0_53;
    assign Result[40] = multiplier_in32bit_alu_output_r_1_0_52;
    assign Result[39] = multiplier_in32bit_alu_output_r_1_0_51;
    assign Result[38] = multiplier_in32bit_alu_output_r_1_0_50;
    assign Result[37] = multiplier_in32bit_alu_output_r_1_0_49;
    assign Result[36] = multiplier_in32bit_alu_output_r_1_0_48;
    assign Result[35] = multiplier_in32bit_alu_output_r_1_0_47;
    assign Result[34] = multiplier_in32bit_alu_output_r_1_0_46;
    assign Result[33] = multiplier_in32bit_alu_output_r_1_0_45;
    assign Result[32] = multiplier_in32bit_alu_output_r_1_0_44;
    assign Result[31] = multiplier_in32bit_alu_output_r_1_0_43;
    assign Result[30] = multiplier_in32bit_alu_output_r_1_0_42;
    assign Result[29] = multiplier_in32bit_alu_output_r_1_0_41;
    assign Result[28] = multiplier_in32bit_alu_output_r_1_0_40;
    assign Result[27] = multiplier_in32bit_alu_output_r_1_0_39;
    assign Result[26] = multiplier_in32bit_alu_output_r_1_0_38;
    assign Result[25] = multiplier_in32bit_alu_output_r_1_0_37;
    assign Result[24] = multiplier_in32bit_alu_output_r_1_0_36;
    assign Result[23] = multiplier_in32bit_alu_output_r_1_0_35;
    assign Result[22] = multiplier_in32bit_alu_output_r_1_0_34;
    assign Result[21] = multiplier_in32bit_alu_output_r_1_0_33;
    assign Result[20] = multiplier_in32bit_alu_output_r_1_0_32;
    assign Result[19] = multiplier_in32bit_alu_output_r_1_0_31;
    assign Result[18] = multiplier_in32bit_alu_output_r_1_0_30;
    assign Result[17] = multiplier_in32bit_alu_output_r_1_0_29;
    assign Result[16] = multiplier_in32bit_alu_output_r_1_0_28;
    assign Result[15] = multiplier_in32bit_alu_output_r_1_0_27;
    assign Result[14] = multiplier_in32bit_alu_output_r_1_0_26;
    assign Result[13] = multiplier_in32bit_alu_output_r_1_0_25;
    assign Result[12] = multiplier_in32bit_alu_output_r_1_0_24;
    assign Result[11] = multiplier_in32bit_alu_output_r_1_0_23;
    assign Result[10] = multiplier_in32bit_alu_output_r_1_0_22;
    assign Result[9] = multiplier_in32bit_alu_output_r_1_0_21;
    assign Result[8] = multiplier_in32bit_alu_output_r_1_0_20;
    assign Result[7] = multiplier_in32bit_alu_output_r_1_0_19;
    assign Result[6] = multiplier_in32bit_alu_output_r_1_0_18;
    assign Result[5] = multiplier_in32bit_alu_output_r_1_0_17;
    assign Result[4] = multiplier_in32bit_alu_output_r_1_0_16;
    assign Result[3] = multiplier_in32bit_alu_output_r_1_0_15;
    assign Result[2] = multiplier_in32bit_alu_output_r_1_0_14;
    assign Result[1] = multiplier_in32bit_alu_output_r_1_0_13;
    assign Result[0] = multiplier_in32bit_alu_output_r_1_0_12;


    // exemplar begin
    // exemplar end

endmodule
