/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 4.9 */
/* Thu Dec 19 11:41:06 2024 */

/* parameterized module instance */
multiplier_in32bit __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), 
    .DataB( ), .Result( ));
