/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 3.5 */
/* Thu Sep 19 20:49:19 2024 */

/* parameterized module instance */
sub_ip __ (.DataA( ), .DataB( ), .Result( ));
