/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 3.5 */
/* D:\TOOL\LatticeDiamond\diamond\3.13\ispfpga\bin\nt64\scuba.exe -w -n sub_ip -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type sub -width 32 -unsigned -pipeline 0 -fdc D:/FreeWork/df1_demo/gpx2/src/ip/df1_lidar_ip/sub_ip/sub_ip.fdc  */
/* Thu Sep 19 20:49:19 2024 */


`timescale 1 ns / 1 ps
module sub_ip (DataA, DataB, Result)/* synthesis NGD_DRC_MASK=1 */;
    input wire [31:0] DataA;
    input wire [31:0] DataB;
    output wire [31:0] Result;

    wire precin;
    wire co0;
    wire co1;
    wire co2;
    wire co3;
    wire co4;
    wire co5;
    wire co6;
    wire co7;
    wire co8;
    wire co9;
    wire co10;
    wire co11;
    wire co12;
    wire co13;
    wire co14;
    wire scuba_vhi;
    wire scuba_vlo;
    wire co15;

    defparam precin_inst99.INJECT1_1 = "NO" ;
    defparam precin_inst99.INJECT1_0 = "NO" ;
    defparam precin_inst99.INIT1 =  16'h0000 ;
    defparam precin_inst99.INIT0 =  16'h0000 ;
    CCU2C precin_inst99 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(precin));

    defparam addsub_0.INJECT1_1 = "NO" ;
    defparam addsub_0.INJECT1_0 = "NO" ;
    defparam addsub_0.INIT1 =  16'h99AA ;
    defparam addsub_0.INIT0 =  16'h99AA ;
    CCU2C addsub_0 (.A0(scuba_vhi), .A1(DataA[0]), .B0(scuba_vlo), .B1(DataB[0]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(precin), .S0(), .S1(Result[0]), .COUT(co0));

    defparam addsub_1.INJECT1_1 = "NO" ;
    defparam addsub_1.INJECT1_0 = "NO" ;
    defparam addsub_1.INIT1 =  16'h99AA ;
    defparam addsub_1.INIT0 =  16'h99AA ;
    CCU2C addsub_1 (.A0(DataA[1]), .A1(DataA[2]), .B0(DataB[1]), .B1(DataB[2]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co0), .S0(Result[1]), .S1(Result[2]), .COUT(co1));

    defparam addsub_2.INJECT1_1 = "NO" ;
    defparam addsub_2.INJECT1_0 = "NO" ;
    defparam addsub_2.INIT1 =  16'h99AA ;
    defparam addsub_2.INIT0 =  16'h99AA ;
    CCU2C addsub_2 (.A0(DataA[3]), .A1(DataA[4]), .B0(DataB[3]), .B1(DataB[4]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co1), .S0(Result[3]), .S1(Result[4]), .COUT(co2));

    defparam addsub_3.INJECT1_1 = "NO" ;
    defparam addsub_3.INJECT1_0 = "NO" ;
    defparam addsub_3.INIT1 =  16'h99AA ;
    defparam addsub_3.INIT0 =  16'h99AA ;
    CCU2C addsub_3 (.A0(DataA[5]), .A1(DataA[6]), .B0(DataB[5]), .B1(DataB[6]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co2), .S0(Result[5]), .S1(Result[6]), .COUT(co3));

    defparam addsub_4.INJECT1_1 = "NO" ;
    defparam addsub_4.INJECT1_0 = "NO" ;
    defparam addsub_4.INIT1 =  16'h99AA ;
    defparam addsub_4.INIT0 =  16'h99AA ;
    CCU2C addsub_4 (.A0(DataA[7]), .A1(DataA[8]), .B0(DataB[7]), .B1(DataB[8]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co3), .S0(Result[7]), .S1(Result[8]), .COUT(co4));

    defparam addsub_5.INJECT1_1 = "NO" ;
    defparam addsub_5.INJECT1_0 = "NO" ;
    defparam addsub_5.INIT1 =  16'h99AA ;
    defparam addsub_5.INIT0 =  16'h99AA ;
    CCU2C addsub_5 (.A0(DataA[9]), .A1(DataA[10]), .B0(DataB[9]), .B1(DataB[10]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co4), .S0(Result[9]), .S1(Result[10]), .COUT(co5));

    defparam addsub_6.INJECT1_1 = "NO" ;
    defparam addsub_6.INJECT1_0 = "NO" ;
    defparam addsub_6.INIT1 =  16'h99AA ;
    defparam addsub_6.INIT0 =  16'h99AA ;
    CCU2C addsub_6 (.A0(DataA[11]), .A1(DataA[12]), .B0(DataB[11]), .B1(DataB[12]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co5), .S0(Result[11]), .S1(Result[12]), .COUT(co6));

    defparam addsub_7.INJECT1_1 = "NO" ;
    defparam addsub_7.INJECT1_0 = "NO" ;
    defparam addsub_7.INIT1 =  16'h99AA ;
    defparam addsub_7.INIT0 =  16'h99AA ;
    CCU2C addsub_7 (.A0(DataA[13]), .A1(DataA[14]), .B0(DataB[13]), .B1(DataB[14]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co6), .S0(Result[13]), .S1(Result[14]), .COUT(co7));

    defparam addsub_8.INJECT1_1 = "NO" ;
    defparam addsub_8.INJECT1_0 = "NO" ;
    defparam addsub_8.INIT1 =  16'h99AA ;
    defparam addsub_8.INIT0 =  16'h99AA ;
    CCU2C addsub_8 (.A0(DataA[15]), .A1(DataA[16]), .B0(DataB[15]), .B1(DataB[16]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co7), .S0(Result[15]), .S1(Result[16]), .COUT(co8));

    defparam addsub_9.INJECT1_1 = "NO" ;
    defparam addsub_9.INJECT1_0 = "NO" ;
    defparam addsub_9.INIT1 =  16'h99AA ;
    defparam addsub_9.INIT0 =  16'h99AA ;
    CCU2C addsub_9 (.A0(DataA[17]), .A1(DataA[18]), .B0(DataB[17]), .B1(DataB[18]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co8), .S0(Result[17]), .S1(Result[18]), .COUT(co9));

    defparam addsub_10.INJECT1_1 = "NO" ;
    defparam addsub_10.INJECT1_0 = "NO" ;
    defparam addsub_10.INIT1 =  16'h99AA ;
    defparam addsub_10.INIT0 =  16'h99AA ;
    CCU2C addsub_10 (.A0(DataA[19]), .A1(DataA[20]), .B0(DataB[19]), .B1(DataB[20]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co9), .S0(Result[19]), .S1(Result[20]), .COUT(co10));

    defparam addsub_11.INJECT1_1 = "NO" ;
    defparam addsub_11.INJECT1_0 = "NO" ;
    defparam addsub_11.INIT1 =  16'h99AA ;
    defparam addsub_11.INIT0 =  16'h99AA ;
    CCU2C addsub_11 (.A0(DataA[21]), .A1(DataA[22]), .B0(DataB[21]), .B1(DataB[22]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co10), .S0(Result[21]), .S1(Result[22]), .COUT(co11));

    defparam addsub_12.INJECT1_1 = "NO" ;
    defparam addsub_12.INJECT1_0 = "NO" ;
    defparam addsub_12.INIT1 =  16'h99AA ;
    defparam addsub_12.INIT0 =  16'h99AA ;
    CCU2C addsub_12 (.A0(DataA[23]), .A1(DataA[24]), .B0(DataB[23]), .B1(DataB[24]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co11), .S0(Result[23]), .S1(Result[24]), .COUT(co12));

    defparam addsub_13.INJECT1_1 = "NO" ;
    defparam addsub_13.INJECT1_0 = "NO" ;
    defparam addsub_13.INIT1 =  16'h99AA ;
    defparam addsub_13.INIT0 =  16'h99AA ;
    CCU2C addsub_13 (.A0(DataA[25]), .A1(DataA[26]), .B0(DataB[25]), .B1(DataB[26]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co12), .S0(Result[25]), .S1(Result[26]), .COUT(co13));

    defparam addsub_14.INJECT1_1 = "NO" ;
    defparam addsub_14.INJECT1_0 = "NO" ;
    defparam addsub_14.INIT1 =  16'h99AA ;
    defparam addsub_14.INIT0 =  16'h99AA ;
    CCU2C addsub_14 (.A0(DataA[27]), .A1(DataA[28]), .B0(DataB[27]), .B1(DataB[28]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co13), .S0(Result[27]), .S1(Result[28]), .COUT(co14));

    defparam addsub_15.INJECT1_1 = "NO" ;
    defparam addsub_15.INJECT1_0 = "NO" ;
    defparam addsub_15.INIT1 =  16'h99AA ;
    defparam addsub_15.INIT0 =  16'h99AA ;
    CCU2C addsub_15 (.A0(DataA[29]), .A1(DataA[30]), .B0(DataB[29]), .B1(DataB[30]), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co14), .S0(Result[29]), .S1(Result[30]), .COUT(co15));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam addsub_16.INJECT1_1 = "NO" ;
    defparam addsub_16.INJECT1_0 = "NO" ;
    defparam addsub_16.INIT1 =  16'h99AA ;
    defparam addsub_16.INIT0 =  16'h99AA ;
    CCU2C addsub_16 (.A0(DataA[31]), .A1(scuba_vlo), .B0(DataB[31]), .B1(scuba_vlo), 
        .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), 
        .CIN(co15), .S0(Result[31]), .S1(), .COUT());



    // exemplar begin
    // exemplar end

endmodule
