/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Thu Oct 17 20:20:37 2024 */

/* parameterized module instance */
eth_pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
